//////////////////////////////////////////////////////////
// Copyright@ 2009 Airoha.  All right reserved.
//////////////////////////////////////////////////////////

#ifndef _KEYPAD_HAL_H_
#define _KEYPAD_HAL_H_

VOID KeypadSetDebounce(BOOL value);

#define READ_KEYB0DEBOUNCE(val)   	HC_SFR_READ_BY_FB (FBOFFS_RO_DEBOUNCE_DO_B0, val)
#define READ_KEYB0LATCH(val)  		HC_SFR_READ_BY_FB (FBOFFS_RO_DEBOUNCE_LATCH_B0, val)
#define SET_KEYB0LATCHRD(keyMask) 	HC_SFR_WRITE_BY_FB(FBOFFS_WO_DEBOUNCE_LATCHRD_B0, keyMask)

#define READ_KEYB1DEBOUNCE(val)		HC_SFR_READ_BY_FB (FBOFFS_RO_DEBOUNCE_DO_B1, val)
#define READ_KEYB1LATCH(val)		HC_SFR_READ_BY_FB (FBOFFS_RO_DEBOUNCE_LATCH_B1, val)
#define SET_KEYB1LATCHRD(keyMask) 	HC_SFR_WRITE_BY_FB(FBOFFS_WO_DEBOUNCE_LATCHRD_B1, keyMask)

#define READ_KEYB2DEBOUNCE(val) 	HC_SFR_READ_BY_FB (FBOFFS_RO_DEBOUNCE_DO_B2, val)
#define READ_KEYB2LATCH(val)		HC_SFR_READ_BY_FB (FBOFFS_RO_DEBOUNCE_LATCH_B2, val)
#define SET_KEYB2LATCHRD(keyMask)	HC_SFR_WRITE_BY_FB(FBOFFS_WO_DEBOUNCE_LATCHRD_B2, keyMask)

#define READ_KEYB3DEBOUNCE(val) 	HC_SFR_READ_BY_FB (FBOFFS_RO_DEBOUNCE_DO_B3, val)
#define READ_KEYB3LATCH(val)		HC_SFR_READ_BY_FB (FBOFFS_RO_DEBOUNCE_LATCH_B3, val)
#define SET_KEYB3LATCHRD(keyMask)	HC_SFR_WRITE_BY_FB(FBOFFS_WO_DEBOUNCE_LATCHRD_B3, keyMask)

#define READ_WAKEUP_LATCH(val)  	HC_SFR_READ_BY_FB (FBOFFS_WO_WAKEUP_DEBOUNCE_DO_LATCH, val)
#define READ_WAKEUP_DEBOUNCE(val) 	HC_SFR_READ_BY_FB (FBOFFS_RO_WAKEUP_DEBOUNCE_DO,val)
#define SET_WAKEUP_LATCHRD(val) 	HC_SFR_WRITE_BY_FB(FBOFFS_RO_WAKEUP_DEBOUNCE_RD, val)

#endif
