#ifndef _HC_CMD_HDLR_PROTOTYPE_
#define _HC_CMD_HDLR_PROTOTYPE_
#if !defined(_HC_C) && !defined(_HC_FLASH_C_)
#error "Only allow to be included by hc.c or hc.flash.c"
#endif
#include "config.h"
#include "ctlr_config.h"
#include "cpu.h"
#include "hc.h"

#if LE_SUPPORTED_CONTROLLER
EXTERN SYS_ERRCODE HC_HciCmdRelayToLL_ByCH(HC_CMD_MSG_STRU_PTR pCmdMsg);
EXTERN SYS_ERRCODE HC_HciCmdRelayToLL(HC_CMD_MSG_STRU_PTR pCmdMsg);
#endif
EXTERN SYS_ERRCODE HC_HciRejectCmdHdlr(HC_CMD_MSG_STRU_PTR pCmdMsg);
EXTERN SYS_ERRCODE HC_HciUnknownCmdHdlr(HC_CMD_MSG_STRU_PTR pCmdMsg);

/* OGF 0x01 */
EXTERN SYS_ERRCODE HC_HciDisconnCmdHdlr(HC_CMD_MSG_STRU_PTR pCmdMsg);
EXTERN SYS_ERRCODE HC_HciRdRemoteVerInfoCmdHdlr(HC_CMD_MSG_STRU_PTR pCmdMsg);


/* OGF 0x03 */
EXTERN SYS_ERRCODE HC_HciSetEvtMaskCmdHdlr(HC_CMD_MSG_STRU_PTR pCmdMsg);
EXTERN SYS_ERRCODE HC_HciRstCmdHdlr(HC_CMD_MSG_STRU_PTR pCmdMsg);
EXTERN SYS_ERRCODE HC_HciRdLeHostSuppCmdHdlr(HC_CMD_MSG_STRU_PTR pCmdMsg);
EXTERN SYS_ERRCODE HC_HciWrLeHostSuppCmdHdlr(HC_CMD_MSG_STRU_PTR pCmdMsg);

/* OGF 0x04 */
EXTERN SYS_ERRCODE HC_HciRdLocalVerInfoCmdHdlr(HC_CMD_MSG_STRU_PTR pCmdMsg);
EXTERN SYS_ERRCODE HC_HciRdLocalSuppFeaCmdHdlr(HC_CMD_MSG_STRU_PTR pCmdMsg);
EXTERN SYS_ERRCODE HC_HciRdBufSizeCmdHdlr(HC_CMD_MSG_STRU_PTR pCmdMsg);
EXTERN SYS_ERRCODE HC_HciRdBdAddrCmdHdlr(HC_CMD_MSG_STRU_PTR pCmdMsg);

/* OGF 0x08 */
EXTERN SYS_ERRCODE HC_HciLeSetEvtMaskCmdHdlr(HC_CMD_MSG_STRU_PTR pCmdMsg);
EXTERN SYS_ERRCODE HC_HciLeRdBufSizeCmdHdlr(HC_CMD_MSG_STRU_PTR pCmdMsg);
EXTERN SYS_ERRCODE HC_HciLeRdLocalSuppFeaCmdHdlr(HC_CMD_MSG_STRU_PTR pCmdMsg);
EXTERN SYS_ERRCODE HC_HciLeSetRandAddrCmdHdlr(HC_CMD_MSG_STRU_PTR pCmdMsg);
EXTERN SYS_ERRCODE HC_HciLeRdAdvChTxPwrCmdHdlr(HC_CMD_MSG_STRU_PTR pCmdMsg);
EXTERN SYS_ERRCODE HC_HciLeRdWhiteListSizeCmdHdlr(HC_CMD_MSG_STRU_PTR pCmdMsg);
EXTERN SYS_ERRCODE HC_HciLeClrWhiteListCmdHdlr(HC_CMD_MSG_STRU_PTR pCmdMsg);
EXTERN SYS_ERRCODE HC_HciLeAddDeviceToWhiteListCmdHdlr(HC_CMD_MSG_STRU_PTR pCmdMsg);
EXTERN SYS_ERRCODE HC_HciLeRmDeviceFromWhiteListCmdHdlr(HC_CMD_MSG_STRU_PTR pCmdMsg);
EXTERN SYS_ERRCODE HC_HciLeRdChMapCmdHdlr(HC_CMD_MSG_STRU_PTR pCmdMsg);
EXTERN SYS_ERRCODE HC_HciLeRandCmdHdlr(HC_CMD_MSG_STRU_PTR pCmdMsg);
EXTERN SYS_ERRCODE HC_HciLeLtkReqReplyCmdHdlr(HC_CMD_MSG_STRU_PTR pCmdMsg);
EXTERN SYS_ERRCODE HC_HciLeLtkReqNegReplyCmdHdlr(HC_CMD_MSG_STRU_PTR pCmdMsg);
EXTERN SYS_ERRCODE HC_HciLeRdSuppStateCmdHdlr(HC_CMD_MSG_STRU_PTR pCmdMsg);

#endif /* _HC_CMD_HDLR_PROTOTYPE_ */

