#ifndef _HC_CMD_HDLR_H_
#define _HC_CMD_HDLR_H_
/*
 * AIROHA Bluetooth Device Firmware
 * COPYRIGHT (C) 2014 AIROHA TECHNOLOGY CORP. CO., LTD. ALL RIGHTS RESERVED
 *
 * hc_cmd_hdlr.h defines the HC command handlers based on COMMAND SUPPORT
 * definitions.
 *
 * Programmer : CharlesSu@airoha.com.tw, Ext.2882
 */
#include "bt_config.h"



////////////////////////////////////////////////////////////////////////////////
// OGF : 0x03 Controller & Baseband Commands ///////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
/* OCF : 0x006C*/
#if (HCI_READ_LE_HOST_SUPPORT_COMMAND_SUPPORTED)
#define HCI_READ_LE_HOST_SUPPORT_COMMAND_HDLR HC_HciRdLeHostSuppCmdHdlr
#else
#define HCI_READ_LE_HOST_SUPPORT_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x006D*/
#if (HCI_WRITE_LE_HOST_SUPPORT_COMMAND_SUPPORTED)
#define HCI_WRITE_LE_HOST_SUPPORT_COMMAND_HDLR HC_HciWrLeHostSuppCmdHdlr
#else
#define HCI_WRITE_LE_HOST_SUPPORT_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif



////////////////////////////////////////////////////////////////////////////////
// OGF : 0x04 Informational Parameters /////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
/* OCF : 0x0001 */
#if (HCI_READ_LOCAL_VERSION_INFORMATION_COMMAND_SUPPORTED)
#define HCI_READ_LOCAL_VERSION_INFORMATION_COMMAND_HDLR HC_HciRdLocalVerInfoCmdHdlr
#else
#define HCI_READ_LOCAL_VERSION_INFORMATION_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0003 */
#if (HCI_READ_LOCAL_SUPPORTED_FEATURES_COMMAND_SUPPORTED)
#define HCI_READ_LOCAL_SUPPORTED_FEATURES_COMMAND_HDLR HC_HciRdLocalSuppFeaCmdHdlr
#else
#define HCI_READ_LOCAL_SUPPORTED_FEATURES_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0004 */
#if (HCI_READ_LOCAL_EXTENDED_FEATURES_COMMAND_SUPPORTED)
#define HCI_READ_LOCAL_EXTENDED_FEATURES_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_READ_LOCAL_EXTENDED_FEATURES_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0005 */
#if (HCI_READ_BUFFER_SIZE_COMMAND_SUPPORTED)
#define HCI_READ_BUFFER_SIZE_COMMAND_HDLR HC_HciRdBufSizeCmdHdlr
#else
#define HCI_READ_BUFFER_SIZE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0009 */
#if (HCI_READ_BD_ADDR_COMMAND_SUPPORTED)
#define HCI_READ_BD_ADDR_COMMAND_HDLR HC_HciRdBdAddrCmdHdlr
#else
#define HCI_READ_BD_ADDR_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x000A */
#if (HCI_READ_DATA_BLOCK_SIZE_COMMAND_SUPPORTED)
#define HCI_READ_DATA_BLOCK_SIZE_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_READ_DATA_BLOCK_SIZE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x000B */
#if (HCI_READ_LOCAL_SUPPORTED_CODECS_COMMAND_SUPPORTED)
#define HCI_READ_LOCAL_SUPPORTED_CODECS_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_READ_LOCAL_SUPPORTED_CODECS_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif



////////////////////////////////////////////////////////////////////////////////
// OGF : 0x08 LE Controller Commands ///////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
/* OCF : 0x0001 */
#if (HCI_LE_SET_EVENT_MASK_COMMAND_SUPPORTED)
#define HCI_LE_SET_EVENT_MASK_COMMAND_HDLR HC_HciLeSetEvtMaskCmdHdlr
#else
#define HCI_LE_SET_EVENT_MASK_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0002 */
#if (HCI_LE_READ_BUFFER_SIZE_COMMAND_SUPPORTED)
#define HCI_LE_READ_BUFFER_SIZE_COMMAND_HDLR HC_HciLeRdBufSizeCmdHdlr
#else
#define HCI_LE_READ_BUFFER_SIZE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0004 */
#if (HCI_LE_READ_LOCAL_SUPPORTED_FEATURES_COMMAND_SUPPORTED)
#define HCI_LE_READ_LOCAL_SUPPORTED_FEATURES_COMMAND_HDLR HC_HciLeRdLocalSuppFeaCmdHdlr
#else
#define HCI_LE_READ_LOCAL_SUPPORTED_FEATURES_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0005 */
#if (HCI_LE_SET_RANDOM_ADDRESS_COMMAND_SUPPORTED)
#define HCI_LE_SET_RANDOM_ADDRESS_COMMAND_HDLR HC_HciLeSetRandAddrCmdHdlr
#else
#define HCI_LE_SET_RANDOM_ADDRESS_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0006 */
#if (HCI_LE_SET_ADVERTISING_PARAMETERS_COMMAND_SUPPORTED)
#define HCI_LE_SET_ADVERTISING_PARAMETERS_COMMAND_HDLR HC_HciCmdRelayToLL
#else
#define HCI_LE_SET_ADVERTISING_PARAMETERS_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0007 */
#if (HCI_LE_READ_ADVERTISING_CHANNEL_TX_POWER_COMMAND_SUPPORTED)
#define HCI_LE_READ_ADVERTISING_CHANNEL_TX_POWER_COMMAND_HDLR HC_HciLeRdAdvChTxPwrCmdHdlr
#else
#define HCI_LE_READ_ADVERTISING_CHANNEL_TX_POWER_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0008 */
#if (HCI_LE_SET_ADVERTISING_DATA_COMMAND_SUPPORTED)
#define HCI_LE_SET_ADVERTISING_DATA_COMMAND_HDLR HC_HciCmdRelayToLL
#else
#define HCI_LE_SET_ADVERTISING_DATA_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0009 */
#if (HCI_LE_SET_SCAN_RESPONSE_DATA_COMMAND_SUPPORTED)
#define HCI_LE_SET_SCAN_RESPONSE_DATA_COMMAND_HDLR HC_HciCmdRelayToLL
#else
#define HCI_LE_SET_SCAN_RESPONSE_DATA_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x000A */
#if (HCI_LE_SET_ADVERTISE_ENABLE_COMMAND_SUPPORTED)
#define HCI_LE_SET_ADVERTISE_ENABLE_COMMAND_HDLR HC_HciCmdRelayToLL
#else
#define HCI_LE_SET_ADVERTISE_ENABLE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x000B */
#if (HCI_LE_SET_SCAN_PARAMETERS_COMMAND_SUPPORTED)
#define HCI_LE_SET_SCAN_PARAMETERS_COMMAND_HDLR HC_HciCmdRelayToLL
#else
#define HCI_LE_SET_SCAN_PARAMETERS_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x000C */
#if (HCI_LE_SET_SCAN_ENABLE_COMMAND_SUPPORTED)
#define HCI_LE_SET_SCAN_ENABLE_COMMAND_HDLR HC_HciCmdRelayToLL
#else
#define HCI_LE_SET_SCAN_ENABLE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x000D */
#if (HCI_LE_CREATE_CONNECTION_COMMAND_SUPPORTED)
#define HCI_LE_CREATE_CONNECTION_COMMAND_HDLR HC_HciCmdRelayToLL
#else
#define HCI_LE_CREATE_CONNECTION_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x000E */
#if (HCI_LE_CREATE_CONNECTION_CANCEL_COMMAND_SUPPORTED)
#define HCI_LE_CREATE_CONNECTION_CANCEL_COMMAND_HDLR HC_HciCmdRelayToLL
#else
#define HCI_LE_CREATE_CONNECTION_CANCEL_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x000F */
#if (HCI_LE_READ_WHITE_LIST_SIZE_COMMAND_SUPPORTED)
#define HCI_LE_READ_WHITE_LIST_SIZE_COMMAND_HDLR HC_HciLeRdWhiteListSizeCmdHdlr
#else
#define HCI_LE_READ_WHITE_LIST_SIZE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0010 */
#if (HCI_LE_CLEAR_WHITE_LIST_COMMAND_SUPPORTED)
#define HCI_LE_CLEAR_WHITE_LIST_COMMAND_HDLR HC_HciLeClrWhiteListCmdHdlr
#else
#define HCI_LE_CLEAR_WHITE_LIST_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0011 */
#if (HCI_LE_ADD_DEVICE_TO_WHITE_LIST_COMMAND_SUPPORTED)
#define HCI_LE_ADD_DEVICE_TO_WHITE_LIST_COMMAND_HDLR HC_HciLeAddDeviceToWhiteListCmdHdlr
#else
#define HCI_LE_ADD_DEVICE_TO_WHITE_LIST_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0012 */
#if (HCI_LE_REMOVE_DEVICE_FROM_WHITE_LIST_COMMAND_SUPPORTED)
#define HCI_LE_REMOVE_DEVICE_FROM_WHITE_LIST_COMMAND_HDLR HC_HciLeRmDeviceFromWhiteListCmdHdlr
#else
#define HCI_LE_REMOVE_DEVICE_FROM_WHITE_LIST_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0013 */
#if (HCI_LE_CONNECTION_UPDATE_COMMAND_SUPPORTED)
#define HCI_LE_CONNECTION_UPDATE_COMMAND_HDLR HC_HciCmdRelayToLL_ByCH
#else
#define HCI_LE_CONNECTION_UPDATE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0014 */
#if (HCI_LE_SET_HOST_CHANNEL_CLASSIFICATION_COMMAND_SUPPORTED)
#define HCI_LE_SET_HOST_CHANNEL_CLASSIFICATION_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_LE_SET_HOST_CHANNEL_CLASSIFICATION_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0015 */
#if (HCI_LE_READ_CHANNEL_MAP_COMMAND_SUPPORTED)
#define HCI_LE_READ_CHANNEL_MAP_COMMAND_HDLR HC_HciCmdRelayToLL_ByCH
#else
#define HCI_LE_READ_CHANNEL_MAP_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0016 */
#if (HCI_LE_READ_REMOTE_USED_FEATURES_COMMAND_SUPPORTED)
#define HCI_LE_READ_REMOTE_USED_FEATURES_COMMAND_HDLR HC_HciCmdRelayToLL_ByCH
#else
#define HCI_LE_READ_REMOTE_USED_FEATURES_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0017 */
#if (HCI_LE_ENCRYPT_COMMAND_SUPPORTED)
#define HCI_LE_ENCRYPT_COMMAND_HDLR HC_HciCmdRelayToLL
#else
#define HCI_LE_ENCRYPT_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0018 */
#if (HCI_LE_RAND_COMMAND_SUPPORTED)
#define HCI_LE_RAND_COMMAND_HDLR HC_HciLeRandCmdHdlr
#else
#define HCI_LE_RAND_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0019 */
#if (HCI_LE_START_ENCRYPTION_COMMAND_SUPPORTED)
#define HCI_LE_START_ENCRYPTION_COMMAND_HDLR HC_HciCmdRelayToLL_ByCH
#else
#define HCI_LE_START_ENCRYPTION_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x001A */
#if (HCI_LE_LONG_TERM_KEY_REQUEST_REPLY_COMMAND_SUPPORTED)
#define HCI_LE_LONG_TERM_KEY_REQUEST_REPLY_COMMAND_HDLR HC_HciCmdRelayToLL_ByCH
#else
#define HCI_LE_LONG_TERM_KEY_REQUEST_REPLY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x001B */
#if (HCI_LE_LONG_TERM_KEY_REQUEST_NEGATIVE_REPLY_COMMAND_SUPPORTED)
#define HCI_LE_LONG_TERM_KEY_REQUEST_NEGATIVE_REPLY_COMMAND_HDLR HC_HciCmdRelayToLL_ByCH
#else
#define HCI_LE_LONG_TERM_KEY_REQUEST_NEGATIVE_REPLY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x001C */
#if (HCI_LE_READ_SUPPORTED_STATES_COMMAND_SUPPORTED)
#define HCI_LE_READ_SUPPORTED_STATES_COMMAND_HDLR HC_HciLeRdSuppStateCmdHdlr
#else
#define HCI_LE_READ_SUPPORTED_STATES_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x001D */
#if (HCI_LE_RECEIVER_TEST_COMMAND_SUPPORTED)
#define HCI_LE_RECEIVER_TEST_COMMAND_HDLR HC_HciCmdRelayToLL
#else
#define HCI_LE_RECEIVER_TEST_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x001E */
#if (HCI_LE_TRANSMITTER_TEST_COMMAND_SUPPORTED)
#define HCI_LE_TRANSMITTER_TEST_COMMAND_HDLR HC_HciCmdRelayToLL
#else
#define HCI_LE_TRANSMITTER_TEST_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x001F */
#if (HCI_LE_TEST_END_COMMAND_SUPPORTED)
#define HCI_LE_TEST_END_COMMAND_HDLR HC_HciCmdRelayToLL
#else
#define HCI_LE_TEST_END_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0020 */
#if (HCI_LE_REMOTE_CONNECTION_PARAMETER_REQUEST_REPLY_COMMAND_SUPPORTED)
#define HCI_LE_REMOTE_CONNECTION_PARAMETER_REQUEST_REPLY_COMMAND_HDLR HC_HciCmdRelayToLL_ByCH
#else
#define HCI_LE_REMOTE_CONNECTION_PARAMETER_REQUEST_REPLY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0021 */
#if (HCI_LE_REMOTE_CONNECTION_PARAMETER_REQUEST_NEGATIVE_REPLY_COMMAND_SUPPORTED)
#define HCI_LE_REMOTE_CONNECTION_PARAMETER_REQUEST_NEGATIVE_REPLY_COMMAND_HDLR HC_HciCmdRelayToLL_ByCH
#else
#define HCI_LE_REMOTE_CONNECTION_PARAMETER_REQUEST_NEGATIVE_REPLY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0022 */
#if (HCI_LE_SET_DATA_LENGTH_COMMAND_SUPPORTED)
#define HCI_LE_SET_DATA_LENGTH_COMMAND_HDLR HC_HciCmdRelayToLL_ByCH
#else
#define HCI_LE_SET_DATA_LENGTH_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0023 */
#if (HCI_LE_READ_SUGGESTED_DEFAULT_DATA_LENGTH_COMMAND_SUPPORTED)
#define HCI_LE_READ_SUGGESTED_DEFAULT_DATA_LENGTH_COMMAND_HDLR HC_HciCmdRelayToLL
#else
#define HCI_LE_READ_SUGGESTED_DEFAULT_DATA_LENGTH_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0024 */
#if (HCI_LE_WRITE_SUGGESTED_DEFAULT_DATA_LENGTH_COMMAND_SUPPORTED)
#define HCI_LE_WRITE_SUGGESTED_DEFAULT_DATA_LENGTH_COMMAND_HDLR HC_HciCmdRelayToLL
#else
#define HCI_LE_WRITE_SUGGESTED_DEFAULT_DATA_LENGTH_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif


#endif /* _HC_CMD_HDLR_H_ */

