#ifndef __MMI_SCN_H___
#define __MMI_SCN_H___

enum
{
	SCN_HEADSET					= 0x01,
	SCN_HANDSFREE				= 0x02,
	SCN_SERIAL_PORT				= 0x03,
	SCN_LCIF					= 0x04,
	SCN_IAP2					= 0x05,
	SCN_SONGPAL_ANDROID			= 0x06,
	SCN_SONGPAL_IAP2			= 0x07,
	SCN_OBJECT_PUSH				= 0x08,
	SCN_SIM_ACCESS				= 0x09,
	SCN_PHONEBOOK_ACCESS		= 0x0A,
	SCN_MESSAGE_ACCESS			= 0x0B,
	SCN_MESSAGE_NOTIFICATION	= 0x0C,
	SCN_AIR_APP					= 0x0D,
};

enum
{
	//MMI Profile Descriptor
	PROFILE_HEADSET 				= SCN_HEADSET,
	PROFILE_HANDSFREE 				= SCN_HANDSFREE,
	PROFILE_SERIAL_PORT				= SCN_SERIAL_PORT,
	PROFILE_LCIF					= SCN_LCIF,
	PROFILE_IAP2					= SCN_IAP2,
	PROFILE_SONGPAL_ANDROID			= SCN_SONGPAL_ANDROID,
	PROFILE_SONGPAL_IAP2			= SCN_SONGPAL_IAP2,
	PROFILE_OBJECT_PUSH 			= SCN_OBJECT_PUSH,
	PROFILE_SIM_ACCESS 				= SCN_SIM_ACCESS,
	PROFILE_PHONEBOOK_ACCESS 		= SCN_PHONEBOOK_ACCESS,
	PROFILE_MESSAGE_ACCESS 			= SCN_MESSAGE_ACCESS,
	PROFILE_MESSAGE_NOTIFICATION	= SCN_MESSAGE_NOTIFICATION,
	PROFILE_AIR_APP					= SCN_AIR_APP,
	PROFILE_SDAP					= 0x21,
	PROFILE_A2DP					= 0x22,
	PROFILE_AVRCP					= 0x23,
	#ifdef HID_Profile
	PROFILE_HID                     = 0x24,
	#endif
	//SDAP Service Record
	PROFILE_PNP						= 0x30,
	PROFILE_A2DP_SOURCE				= 0x31,
	PROFILE_A2DP_SINK				= 0x32,
	PROFILE_AVRCP_TG				= 0x33,
	PROFILE_AVRCP_CT				= 0x34,
	PROFILE_MPS						= 0x35,
};

#endif //__MMI_SCN_H___
