#ifdef AB1520B

#ifdef DSP_ENABLE
SECTORS_ENUM_MACRO(SECTOR_DSP_PEQ_PARAMETER, &gSector_DspPeqParameter, sizeof(DSP_PEQ_PARAMETER_STRU), CRC_CHK)
#else
SECTORS_ENUM_MACRO(SECTOR_DSP_PEQ_PARAMETER, NULL, 0, CRC_NOT_CHK)
#endif

#ifdef DSP_ENABLE
SECTORS_ENUM_MACRO(SECTOR_DSP_HPF_PARAMETER, &gSector_DspHpfParameter, sizeof(DSP_HPF_PARAMETER_STRU), CRC_CHK)
#else
SECTORS_ENUM_MACRO(SECTOR_DSP_HPF_PARAMETER, NULL, 0, CRC_NOT_CHK)
#endif

#ifdef DSP_ENABLE
SECTORS_ENUM_MACRO(SECTOR_DSP_FUNC_PARAMETER, &gSector_DspFuncParameter, sizeof(DSP_FUNC_PARA_CTL_STRU), CRC_CHK)
#else
SECTORS_ENUM_MACRO(SECTOR_DSP_FUNC_PARAMETER, NULL, 0, CRC_NOT_CHK)
#endif

#endif

#ifdef AB1528C_ONLY
SECTORS_ENUM_MACRO(SECTOR_DSP_ROM, SROM_MC_TRG(HCONST_DSP_ROM), SROM_MC_LEN(HCONST_DSP_ROM), CRC_NOT_CHK)
#else
SECTORS_ENUM_MACRO(SECTOR_DSP_ROM, NULL, 0, CRC_NOT_CHK)
#endif

#if (defined DSP_ENABLE) && (defined SUPPORT_VOICE_PROMPT) && (defined VP_NB_HQ_ENABLE || defined VP_NB_LQ_ENABLE) 
SECTORS_ENUM_MACRO(SECTOR_DSP_VP_NB, &gSector_DspVpNb, sizeof(DSP_VP_NB_STRU), CRC_NOT_CHK)
#else
SECTORS_ENUM_MACRO(SECTOR_DSP_VP_NB, NULL, 0, CRC_NOT_CHK)
#endif