#ifndef __DSP_STATUS_HH__
#define __DSP_STATUS_HH__

typedef enum{
	SDK_DSP_PLAYING_STOPPED,
	SDK_DSP_PLAYING_RINGTONE,
	SDK_DSP_PLAYING_SCO,
	SDK_DSP_PLAYING_VOICEPROMPT,
	SDK_DSP_PLAYING_A2DP,
	SDK_DSP_PLAYING_AUDIO_LINE_IN,
	SDK_DSP_PLAYING_VOICECOMMAND,
	SDK_DSP_PLAYING_AUDIO_FM,
	SDK_DSP_PLAYING_ASYNC_SCO,
} DSP_PLAYING_STATUS;

/*
The API is used to check the playing status of DSP. The reurn value will be one of the following:
	SDK_DSP_PLAYING_STOPPED,
	SDK_DSP_PLAYING_RINGTONE,
	SDK_DSP_PLAYING_SCO,
	SDK_DSP_PLAYING_VOICEPROMPT,
	SDK_DSP_PLAYING_A2DP,
	SDK_DSP_PLAYING_AUDIO_LINE_IN,
	SDK_DSP_PLAYING_VOICECOMMAND,
	SDK_DSP_PLAYING_AUDIO_FM,
	SDK_DSP_PLAYING_ASYNC_SCO
*/
DSP_PLAYING_STATUS SDK_DSP_Playing_Status(void);

#endif
