

enum
{
	SDK_KEY_EVENT_NULL,
	SDK_KEY_EVENT_1,
	SDK_KEY_EVENT_2,
	SDK_KEY_EVENT_3_ROLE_SWITCH_MASTER,
	SDK_KEY_EVENT_4_ROLE_SWITCH_SLAVE,
	SDK_KEY_EVENT_5_INQUIRY,
	SDK_KEY_EVENT_6_GET_REPEAT,
	SDK_KEY_EVENT_7_GET_SHUFFLE,
	SDK_KEY_EVENT_8_KEY_PLAY,
	SDK_KEY_EVENT_9_KEY_FORWARD,
};