
#ifndef _HFP_HANDLER_AG_H_
#define _HFP_HANDLER_AG_H_

enum
{
	HFP_AT_COMMAND_CODE,
};

enum
{
	HFP_AT_COMMAND_CKPD200,
	HFP_AT_COMMAND_VGS,
	HFP_AT_COMMAND_VGM,
	HFP_AT_COMMAND_BRSF,
	HFP_AT_COMMAND_CIND_EQUAL_QUESTION,
	HFP_AT_COMMAND_CIND_QUESTION,
	HFP_AT_COMMAND_CMER_EQUAL,
	HFP_AT_COMMAND_CHLD_EQUAL_QUESTION,
	HFP_AT_COMMAND_CCWA,
	HFP_AT_COMMAND_CLIP,
	HFP_AT_COMMAND_NREC,
	HFP_AT_COMMAND_BIA,
	HFP_AT_COMMAND_CBC,
	HFP_AT_COMMAND_COPS,
	HFP_AT_COMMAND_CMEE,
	HFP_AT_COMMAND_XAPL,
	HFP_AT_COMMAND_XEVENT,
	HFP_AT_COMMAND_IPHONEACCEV,
	HFP_AT_COMMAND_BVRA,
	HFP_AT_COMMAND_BLDN,
	HFP_AT_COMMAND_CSCS,
	HFP_AT_COMMAND_BAC,
	HFP_AT_COMMAND_BCS,
	HFP_AT_COMMAND_BCC,
	HFP_AT_COMMAND_ATA,
	HFP_AT_COMMAND_CHUP,
};

#define HFP_AT_COMMAND_CODE_ARRAY_BASIC		21
#define HFP_AT_COMMAND_CODE_ARRAY_NEGO		3
#define HFP_AT_COMMAND_CODE_ARRAY_AUTO		2

#define HFP_AT_COMMAND_CODE_ARRAY_SIZE		(HFP_AT_COMMAND_CODE_ARRAY_BASIC + HFP_AT_COMMAND_CODE_ARRAY_NEGO + HFP_AT_COMMAND_CODE_ARRAY_AUTO)
#define HFP_AT_COMMAND_CODE_MAX_LENGTH		(14+1)//add one to add a 0x00 at the end of the string;


//misc Flags
#define HFP_HF_SUPPORT_CODEC_NEGO			0x01
#define HFP_HF_USING_CODEC_MSBC				0x02


#endif //_HFP_HANDLER_AG_H_
