/*
00 配對
01 檢查狀態
02 打電話
03 電池電量
04 檢查電池
05 連接狀況
06 重撥
07 語音撥號
08 回撥
09 我可以說甚麼
10 接聽
11 忽略
12 取消
*/


VC_DATA_DEFINE	(PAIRING)
VC_DATA_DEFINE	(CHECK_STATUS)
VC_DATA_DEFINE	(MAKE_A_CALL)
VC_DATA_DEFINE	(BATTERY_LEVEL)
VC_DATA_DEFINE	(CHECK_BATTERY)
VC_DATA_DEFINE	(CONNECTION_STATUS)
VC_DATA_DEFINE	(LAST_CALL_OUT)
VC_DATA_DEFINE	(VOICE_DIAL)
VC_DATA_DEFINE	(RING_BACK)
VC_DATA_DEFINE	(WHAT_CAN_I_SAY)
VC_DATA_DEFINE	(TAKE_THE_CALL)
VC_DATA_DEFINE	(REJECT)
VC_DATA_DEFINE	(CANCEL)
