/*
00 配對
01 檢查電量
02 連接狀況
03 回撥
04 我能說什麼指令
05 接聽
06 拒接
07 取消
*/

VC_DATA_DEFINE	(PAIRING)
VC_DATA_DEFINE	(CHECK_BATTERY)
VC_DATA_DEFINE	(AM_I_CONNECTED)
VC_DATA_DEFINE	(LAST_CALL_OUT)
VC_DATA_DEFINE	(WHAT_CAN_I_SAY)
VC_DATA_DEFINE	(TAKE_THE_CALL)
VC_DATA_DEFINE	(REJECT)
VC_DATA_DEFINE	(CANCEL)
