SECTORS_ENUM_MACRO(SECTOR_MP_PARAMETER, &gSector_MpParameter, sizeof(MP_PARAMETER_STRU), CRC_CHK)

#ifdef AB1520B
SECTORS_ENUM_MACRO(SECTOR_SYS_PATCH_CODE_INIT, &gSector_SysPatchCodeInit, sizeof(PATCH_CODE_INIT_STRU), CRC_CHK)
#endif

#ifndef AB1520B

#ifdef DSP_ENABLE
SECTORS_ENUM_MACRO(SECTOR_DSP_FUNC_PARAMETER, &gSector_DspFuncParameter, sizeof(DSP_FUNC_PARA_CTL_STRU), CRC_CHK)
#else
SECTORS_ENUM_MACRO(SECTOR_DSP_FUNC_PARAMETER, NULL, 0, CRC_NOT_CHK)
#endif

#ifdef DSP_ENABLE
SECTORS_ENUM_MACRO(SECTOR_DSP_PEQ_HPF_PARAMETER_CUSTOM, &gSector_DspPeqHpfParameterCustom, sizeof(SECTOR_DSP_PEQ_HPF_CUSTOM_PARAMETER_STRU), CRC_NOT_CHK)
#else
SECTORS_ENUM_MACRO(SECTOR_DSP_PEQ_HPF_PARAMETER_CUSTOM, NULL, 0, CRC_NOT_CHK)
#endif

SECTORS_ENUM_MACRO(SECTOR_RESERVED_FOR_ORIGINAL_ORDER, NULL, 0, CRC_NOT_CHK)

SECTORS_ENUM_MACRO(SECTOR_MP_PARAMETER_F, &gSector_MpParameter_F, sizeof(MP_PARAMETER_F_STRU), CRC_CHK)
	
#ifdef SUPPORT_VOICE_COMMAND
SECTORS_ENUM_MACRO(SECTOR_VOICE_COMMAND_APD_DATA, &gDriverVoiceCommandAPDData, sizeof(SECTOR_DRIVER_VOICE_COMMAND_APD_STRU), CRC_NOT_CHK)
#else
SECTORS_ENUM_MACRO(SECTOR_VOICE_COMMAND_APD_DATA, NULL, 0, CRC_NOT_CHK)
#endif

#endif
