#ifndef _HC_CMD_HDLR_FLASH_H_
#define _HC_CMD_HDLR_FLASH_H_
/*
 * AIROHA Bluetooth Device Firmware
 * COPYRIGHT (C) 2014 AIROHA TECHNOLOGY CORP. CO., LTD. ALL RIGHTS RESERVED
 *
 * hc_cmd_hdlr.h defines the HC command handlers based on COMMAND SUPPORT
 * definitions.
 *
 * Programmer : CharlesSu@airoha.com.tw, Ext.2882
 */
#include "bt_config_flash.h"



////////////////////////////////////////////////////////////////////////////////
// OGF : 0x01 Link Control Commands ////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
/* OCF : 0x0001 */
#if (HCI_INQUIRY_COMMAND_SUPPORTED)
#define HCI_INQUIRY_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_INQUIRY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0002 */
#if (HCI_INQUIRY_CANCEL_COMMAND_SUPPORTED)
#define HCI_INQUIRY_CANCEL_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_INQUIRY_CANCEL_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0003 */
#if (HCI_PERIODIC_INQUIRY_MODE_COMMAND_SUPPORTED)
#define HCI_PERIODIC_INQUIRY_MODE_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_PERIODIC_INQUIRY_MODE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0004 */
#if (HCI_EXIT_PERIODIC_INQUIRY_MODE_COMMAND_SUPPORTED)
#define HCI_EXIT_PERIODIC_INQUIRY_MODE_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_EXIT_PERIODIC_INQUIRY_MODE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0005 */
#if (HCI_CREATE_CONNECTION_COMMAND_SUPPOTRED)
#define HCI_CREATE_CONNECTION_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_CREATE_CONNECTION_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0006 */
#if (HCI_DISCONNECT_COMMAND_SUPPORTED)
#define HCI_DISCONNECT_COMMAND_HDLR HC_HciCmdRelayToLm_ByCH
#else
#define HCI_DISCONNECT_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0008 */
#if (HCI_CREATE_CONNECTION_CANCEL_COMMAND_SUPPORTED)
#define HCI_CREATE_CONNECTION_CANCEL_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_CREATE_CONNECTION_CANCEL_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0009 */
#if (HCI_ACCEPT_CONNECTION_REQUEST_COMMAND_SUPPORTED)
#define HCI_ACCEPT_CONNECTION_REQUEST_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_ACCEPT_CONNECTION_REQUEST_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x000A */
#if (HCI_REJECT_CONNECTION_REQUEST_COMMAND_SUPPORTED)
#define HCI_REJECT_CONNECTION_REQUEST_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_REJECT_CONNECTION_REQUEST_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x000B */
#if (HCI_LINK_KEY_REQUEST_REPLY_COMMAND_SUPPORTED)
#define HCI_LINK_KEY_REQUEST_REPLY_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_LINK_KEY_REQUEST_REPLY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x000C */
#if (HCI_LINK_KEY_REQUEST_NEGATIVE_REPLY_COMMAND_SUPPORTED)
#define HCI_LINK_KEY_REQUEST_NEGATIVE_REPLY_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_LINK_KEY_REQUEST_NEGATIVE_REPLY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x000D */
#if (HCI_PIN_CODE_REQUEST_REPLY_COMMAND_SUPPORTED)
#define HCI_PIN_CODE_REQUEST_REPLY_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_PIN_CODE_REQUEST_REPLY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x000E */
#if (HCI_PIN_CODE_REQUEST_NEGATIVE_REPLY_COMMAND_SUPPORTED)
#define HCI_PIN_CODE_REQUEST_NEGATIVE_REPLY_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_PIN_CODE_REQUEST_NEGATIVE_REPLY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x000F */
#if (HCI_CHANGE_CONNECTION_PACKET_TYPE_COMMAND_SUPPORTED)
#define HCI_CHANGE_CONNECTION_PACKET_TYPE_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_CHANGE_CONNECTION_PACKET_TYPE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0011 */
#if (HCI_AUTHENTICATION_REQUEST_COMMAND_SUPPORTED)
#define HCI_AUTHENTICATION_REQUEST_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_AUTHENTICATION_REQUEST_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0013 */
#if (HCI_SET_CONNECTION_ENCRYPTION_COMMAND_SUPPORTED)
#define HCI_SET_CONNECTION_ENCRYPTION_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_SET_CONNECTION_ENCRYPTION_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0015 */
#if (HCI_CHANGE_CONNECTION_LINK_KEY_COMMAND_SUPPORTED)
#define HCI_CHANGE_CONNECTION_LINK_KEY_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_CHANGE_CONNECTION_LINK_KEY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0017 */
#if (HCI_MASTER_LINK_KEY_COMMAND_SUPPORTED)
#define HCI_MASTER_LINK_KEY_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_MASTER_LINK_KEY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0019 */
#if (HCI_REMOTE_NAME_REQUEST_COMMAND_SUPPORTED)
#define HCI_REMOTE_NAME_REQUEST_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_REMOTE_NAME_REQUEST_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x001A */
#if (HCI_REMOTE_NAME_REQUEST_CANCEL_COMMAND_SUPPORTED)
#define HCI_REMOTE_NAME_REQUEST_CANCEL_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_REMOTE_NAME_REQUEST_CANCEL_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x001B */
#if (HCI_READ_REMOTE_SUPPORTED_FEATURES_COMMAND_SUPPORTED)
#define HCI_READ_REMOTE_SUPPORTED_FEATURES_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_READ_REMOTE_SUPPORTED_FEATURES_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x001C */
#if (HCI_READ_REMOTE_EXTENDED_FEATURES_COMMAND_SUPPORTED)
#define HCI_READ_REMOTE_EXTENDED_FEATURES_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_READ_REMOTE_EXTENDED_FEATURES_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x001C */
#if (HCI_READ_REMOTE_EXTENDED_FEATURES_COMMAND_SUPPORTED)
#define HCI_READ_REMOTE_EXTENDED_FEATURES_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_READ_REMOTE_EXTENDED_FEATURES_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x001D */
#if (HCI_READ_REMOTE_VERSION_INFORMATION_COMMAND_SUPPORTED)
#define HCI_READ_REMOTE_VERSION_INFORMATION_COMMAND_HDLR HC_HciCmdRelayToLm_ByCH
#else
#define HCI_READ_REMOTE_VERSION_INFORMATION_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x001F */
#if (HCI_READ_CLOCK_OFFSET_COMMAND_SUPPORTED)
#define HCI_READ_CLOCK_OFFSET_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_READ_CLOCK_OFFSET_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0020 */
#if (HCI_READ_LMP_HANDLE_COMMAND_SUPPORTED)
#define HCI_READ_LMP_HANDLE_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_READ_LMP_HANDLE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0028 */
#if (HCI_SETUP_SYNCHRONOUS_CONNECTION_REQUEST_COMMAND_SUPPORTED)
#define HCI_SETUP_SYNCHRONOUS_CONNECTION_REQUEST_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_SETUP_SYNCHRONOUS_CONNECTION_REQUEST_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0029 */
#if (HCI_ACCEPT_SYNCHRONOUS_CONNECTION_REQUEST_COMMAND_SUPPORTED)
#define HCI_ACCEPT_SYNCHRONOUS_CONNECTION_REQUEST_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_ACCEPT_SYNCHRONOUS_CONNECTION_REQUEST_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x002A */
#if (HCI_REJECT_SYNCHRONOUS_CONNECTION_REQUEST_COMMAND_SUPPORTED)
#define HCI_REJECT_SYNCHRONOUS_CONNECTION_REQUEST_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_REJECT_SYNCHRONOUS_CONNECTION_REQUEST_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x002B */
#if (HCI_IO_CAPABILITY_REQUEST_REPLY_COMMAND_SUPPORTED)
#define HCI_IO_CAPABILITY_REQUEST_REPLY_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_IO_CAPABILITY_REQUEST_REPLY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x002C */
#if (HCI_USER_CONFIRMATION_REQUEST_REPLY_COMMAND_SUPPORTED)
#define HCI_USER_CONFIRMATION_REQUEST_REPLY_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_USER_CONFIRMATION_REQUEST_REPLY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x002D */
#if (HCI_USER_CONFIRMATION_REQUEST_NEGATIVE_REPLY_COMMAND_SUPPORTED)
#define HCI_USER_CONFIRMATION_REQUEST_NEGATIVE_REPLY_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_USER_CONFIRMATION_REQUEST_NEGATIVE_REPLY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x002E */
#if (HCI_USER_PASSKEY_REQUEST_REPLY_COMMAND_SUPPORTED)
#define HCI_USER_PASSKEY_REQUEST_REPLY_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_USER_PASSKEY_REQUEST_REPLY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x002F */
#if (HCI_USER_PASSKEY_REQUEST_NEGATIVE_REPLY_COMMAND_SUPPORTED)
#define HCI_USER_PASSKEY_REQUEST_NEGATIVE_REPLY_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_USER_PASSKEY_REQUEST_NEGATIVE_REPLY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0030 */
#if (HCI_REMOTE_OOB_DATA_REQUEST_REPLY_COMMAND_SUPPORTED)
#define HCI_REMOTE_OOB_DATA_REQUEST_REPLY_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_REMOTE_OOB_DATA_REQUEST_REPLY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0033 */
#if (HCI_REMOTE_OOB_DATA_REQUEST_NEGATIVE_REPLY_COMMAND_SUPPORTED)
#define HCI_REMOTE_OOB_DATA_REQUEST_NEGATIVE_REPLY_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_REMOTE_OOB_DATA_REQUEST_NEGATIVE_REPLY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0034 */
#if (HCI_IO_CAPABILITY_REQUEST_NEGATIVE_REPLY_COMMAND_SUPPORTED)
#define HCI_IO_CAPABILITY_REQUEST_NEGATIVE_REPLY_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_IO_CAPABILITY_REQUEST_NEGATIVE_REPLY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0045 */
#if (HCI_REMOTE_OOB_EXTENDED_DATA_REQUEST_REPLY_COMMAND_SUPPORTED)
#define HCI_REMOTE_OOB_EXTENDED_DATA_REQUEST_REPLY_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_REMOTE_OOB_EXTENDED_DATA_REQUEST_REPLY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif



////////////////////////////////////////////////////////////////////////////////
// OGF : 0x02 Link Policy Commands /////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
/* OCF : 0x0001 */
#if (HCI_HOLD_MODE_COMMAND_SUPPORTED)
#define HCI_HOLD_MODE_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_HOLD_MODE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0003 */
#if (HCI_SNIFF_MODE_COMMAND_SUPPORTED)
#define HCI_SNIFF_MODE_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_SNIFF_MODE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0004 */
#if (HCI_EXIT_SNIFF_MODE_COMMAND_SUPPORTED)
#define HCI_EXIT_SNIFF_MODE_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_EXIT_SNIFF_MODE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0005 */
#if (HCI_PARK_STATE_COMMAND_SUPPORTED)
#define HCI_PARK_STATE_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_PARK_STATE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0006 */
#if (HCI_EXIT_PARK_STATE_COMMAND_SUPPORTED)
#define HCI_EXIT_PARK_STATE_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_EXIT_PARK_STATE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0007 */
#if (HCI_QOS_SETUP_COMMAND_SUPPORTED)
#define HCI_QOS_SETUP_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_QOS_SETUP_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0009 */
#if (HCI_ROLE_DISCOVERY_COMMAND_SUPPORTED)
#define HCI_ROLE_DISCOVERY_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_ROLE_DISCOVERY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x000B */
#if (HCI_SWITCH_ROLE_COMMAND_SUPPORTED)
#define HCI_SWITCH_ROLE_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_SWITCH_ROLE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x000C */
#if (HCI_READ_LINK_POLICY_SETTINGS_COMMAND_SUPPORTED)
#define HCI_READ_LINK_POLICY_SETTINGS_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_READ_LINK_POLICY_SETTINGS_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x000D */
#if (HCI_WRITE_LINK_POLICY_SETTINGS_COMMAND_SUPPORTED)
#define HCI_WRITE_LINK_POLICY_SETTINGS_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_WRITE_LINK_POLICY_SETTINGS_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x000E */
#if (HCI_READ_DEFAULT_LINK_POLICY_SETTINGS_COMMAND_SUPPORTED)
#define HCI_READ_DEFAULT_LINK_POLICY_SETTINGS_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_READ_DEFAULT_LINK_POLICY_SETTINGS_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x000F */
#if (HCI_WRITE_DEFAULT_LINK_POLICY_SETTINGS_COMMAND_SUPPORTED)
#define HCI_WRITE_DEFAULT_LINK_POLICY_SETTINGS_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_WRITE_DEFAULT_LINK_POLICY_SETTINGS_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0010 */
#if (HCI_FLOW_SPECIFICATION_COMMAND_SUPPORTED)
#define HCI_FLOW_SPECIFICATION_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_FLOW_SPECIFICATION_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0010 */
#if (HCI_SNIFF_SUBRATING_COMMAND_SUPPORTED)
#define HCI_SNIFF_SUBRATING_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_SNIFF_SUBRATING_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif



////////////////////////////////////////////////////////////////////////////////
// OGF : 0x03 Controller & Baseband Commands ///////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
/* OCF : 0x0001 */
#if (HCI_SET_EVENT_MASK_COMMAND_SUPPORTED)
#define HCI_SET_EVENT_MASK_COMMAND_HDLR HC_HciSetEvtMaskCmdHdlr
#else
#define HCI_SET_EVENT_MASK_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0002 */
#if (HCI_RESET_COMMAND_SUPPORTED)
#define HCI_RESET_COMMAND_HDLR HC_HciRstCmdHdlr_FLASH
#else
#define HCI_RESET_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0005 */
#if (HCI_SET_EVENT_FILTER_COMMAND_SUPPORTED)
#define HCI_SET_EVENT_FILTER_COMMAND_HDLR HC_HciSetEvtFilterCmdHdlr_FLASH
#else
#define HCI_SET_EVENT_FILTER_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

//#warning "implement HCI_FLUSH_COMMAND_HDLR"
/* OCF : 0x0008 */
#if (HCI_FLUSH_COMMAND_SUPPORTED)
#define HCI_FLUSH_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_FLUSH_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0009 */
#if (HCI_READ_PIN_TYPE_COMMAND_SUPPORTED)
#define HCI_READ_PIN_TYPE_COMMAND_HDLR HC_HciRdPinTypeCmdHdlr_FLASH
#else
#define HCI_READ_PIN_TYPE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x000A */
#if (HCI_WRITE_PIN_TYPE_COMMAND_SUPPORTED)
#define HCI_WRITE_PIN_TYPE_COMMAND_HDLR HC_HciWrPinTypeCmdHdlr_FLASH
#else
#define HCI_WRITE_PIN_TYPE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

//#warning "implement HCI_CREATE_NEW_UNIT_KEY_COMMAND_HDLR"
/* OCF : 0x000B */
#if (HCI_CREATE_NEW_UNIT_KEY_COMMAND_SUPPORTED)
#define HCI_CREATE_NEW_UNIT_KEY_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_CREATE_NEW_UNIT_KEY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x000D */
#if (HCI_READ_STORED_LINK_KEY_COMMAND_SUPPORTED)
#define HCI_READ_STORED_LINK_KEY_COMMAND_HDLR HC_HciRdStoredLinkKeyCmdHdlr_FLASH
#else
#define HCI_READ_STORED_LINK_KEY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0011 */
#if (HCI_WRITE_STORED_LINK_KEY_COMMAND_SUPPORTED)
#define HCI_WRITE_STORED_LINK_KEY_COMMAND_HDLR HC_HciWrStoredLinkKeyCmdHdlr_FLASH
#else
#define HCI_WRITE_STORED_LINK_KEY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0012 */
#if (HCI_DELETE_STORED_LINK_KEY_COMMAND_SUPPORTED)
#define HCI_DELETE_STORED_LINK_KEY_COMMAND_HDLR HC_HciDelStoredLinkKeyCmdHdlr_FLASH
#else
#define HCI_DELETE_STORED_LINK_KEY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0013 */
#if (HCI_WRITE_LOCAL_NAME_COMMAND_SUPPORTED)
#define HCI_WRITE_LOCAL_NAME_COMMAND_HDLR HC_HciWrLocalNameCmdHdlr_FLASH
#else
#define HCI_WRITE_LOCAL_NAME_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0014 */
#if (HCI_READ_LOCAL_NAME_COMMAND_SUPPORTED)
#define HCI_READ_LOCAL_NAME_COMMAND_HDLR HC_HciRdLocalNameCmdHdlr_FLASH
#else
#define HCI_READ_LOCAL_NAME_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0015 */
#if (HCI_READ_CONNECTION_ACCEPT_TIMEOUT_COMMAND_SUPPORTED)
#define HCI_READ_CONNECTION_ACCEPT_TIMEOUT_COMMAND_HDLR HC_HciRdConnAcceptToCmdHdlr_FLASH
#else
#define HCI_READ_CONNECTION_ACCEPT_TIMEOUT_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0016 */
#if (HCI_WRITE_CONNECTION_ACCEPT_TIMEOUT_COMMAND_SUPPORTED)
#define HCI_WRITE_CONNECTION_ACCEPT_TIMEOUT_COMMAND_HDLR HC_HciWrConnAcceptToCmdHdlr_FLASH
#else
#define HCI_WRITE_CONNECTION_ACCEPT_TIMEOUT_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0017 */
#if (HCI_READ_PAGE_TIMEOUT_COMMAND_SUPPORTED)
#define HCI_READ_PAGE_TIMEOUT_COMMAND_HDLR HC_HciRdPageToCmdHdlr_FLASH
#else
#define HCI_READ_PAGE_TIMEOUT_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0018 */
#if (HCI_WRITE_PAGE_TIMEOUT_COMMAND_SUPPORTED)
#define HCI_WRITE_PAGE_TIMEOUT_COMMAND_HDLR HC_HciWrPageToCmdHdlr_FLASH
#else
#define HCI_WRITE_PAGE_TIMEOUT_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0019 */
#if (HCI_READ_SCAN_ENABLE_COMMAND_SUPPORTED)
#define HCI_READ_SCAN_ENABLE_COMMAND_HDLR HC_HciRdScanEnableCmdHdlr_FLASH
#else
#define HCI_READ_SCAN_ENABLE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x001A */
#if (HCI_WRITE_SCAN_ENABLE_COMMAND_SUPPORTED)
#define HCI_WRITE_SCAN_ENABLE_COMMAND_HDLR HC_HciWrScanEnableCmdHdlr_FLASH
#else
#define HCI_WRITE_SCAN_ENABLE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x001B */
#if (HCI_READ_PAGE_SCAN_ACTIVITY_COMMAND_SUPPORTED)
#define HCI_READ_PAGE_SCAN_ACTIVITY_COMMAND_HDLR HC_HciRdPageScanActivityCmdHdlr_FLASH
#else
#define HCI_READ_PAGE_SCAN_ACTIVITY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x001C */
#if (HCI_WRITE_PAGE_SCAN_ACTIVITY_COMMAND_SUPPORTED)
#define HCI_WRITE_PAGE_SCAN_ACTIVITY_COMMAND_HDLR HC_HciWrPageScanActivityCmdHdlr_FLASH
#else
#define HCI_WRITE_PAGE_SCAN_ACTIVITY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x001D */
#if (HCI_READ_INQUIRY_SCAN_ACTIVITY_COMMAND_SUPPORTED)
#define HCI_READ_INQUIRY_SCAN_ACTIVITY_COMMAND_HDLR HC_HciRdInqScanActivityCmdHdlr_FLASH
#else
#define HCI_READ_INQUIRY_SCAN_ACTIVITY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x001E */
#if (HCI_WRITE_INQUIRY_SCAN_ACTIVITY_COMMAND_SUPPORTED)
#define HCI_WRITE_INQUIRY_SCAN_ACTIVITY_COMMAND_HDLR HC_HciWrInqScanActivityCmdHdlr_FLASH
#else
#define HCI_WRITE_INQUIRY_SCAN_ACTIVITY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x001F */
#if (HCI_READ_AUTHENTICATION_ENABLE_COMMAND_SUPPORTED)
#define HCI_READ_AUTHENTICATION_ENABLE_COMMAND_HDLR HC_HciRdAuthEnableCmdHdlr_FLASH
#else
#define HCI_READ_AUTHENTICATION_ENABLE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0020 */
#if (HCI_WRITE_AUTHENTICATION_ENABLE_COMMAND_SUPPORTED)
#define HCI_WRITE_AUTHENTICATION_ENABLE_COMMAND_HDLR HC_HciWrAuthEnableCmdHdlr_FLASH
#else
#define HCI_WRITE_AUTHENTICATION_ENABLE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0022 */ /* Deprecate after BT 2.0 */
#if (HCI_WRITE_ENCRYPTION_MODE_COMMAND_SUPPORTED)
#define HCI_WRITE_ENCRYPTION_MODE_COMMAND_HDLR HC_HciWrEncryptModeCmdHdlr_FLASH
#else
#define HCI_WRITE_ENCRYPTION_MODE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0023 */ /* Deprecate after BT 2.0 */
#if (HCI_READ_CLASS_OF_DEVICE_COMMAND_SUPPORTED)
#define HCI_READ_CLASS_OF_DEVICE_COMMAND_HDLR HC_HciRdClassOfDeviceCmdHdlr_FLASH
#else
#define HCI_READ_CLASS_OF_DEVICE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0024 */
#if (HCI_WRITE_CLASS_OF_DEVICE_COMMAND_SUPPORTED)
#define HCI_WRITE_CLASS_OF_DEVICE_COMMAND_HDLR HC_HciWrClassOfDeviceCmdHdlr_FLASH
#else
#define HCI_WRITE_CLASS_OF_DEVICE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0025 */
#if (HCI_READ_VOICE_SETTING_COMMAND_SUPPORTED)
#define HCI_READ_VOICE_SETTING_COMMAND_HDLR HC_HciRdVoiceSetCmdHdlr_FLASH
#else
#define HCI_READ_VOICE_SETTING_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

//#warning "implement HCI_WRITE_VOICE_SETTING_COMMAND_HDLR"
/* OCF : 0x0026 */
#if (HCI_WRITE_VOICE_SETTING_COMMAND_SUPPORTED)
#define HCI_WRITE_VOICE_SETTING_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_WRITE_VOICE_SETTING_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0027 */
#if (HCI_READ_AUTOMATIC_FLUSH_TIMEOUT_COMMAND_SUPPORTED)
#define HCI_READ_AUTOMATIC_FLUSH_TIMEOUT_COMMAND_HDLR HC_HciRdAutoFlushToCmdHdlr_FLASH
#else
#define HCI_READ_AUTOMATIC_FLUSH_TIMEOUT_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0028 */
#if (HCI_WRITE_AUTOMATIC_FLUSH_TIMEOUT_COMMAND_SUPPORTED)
#define HCI_WRITE_AUTOMATIC_FLUSH_TIMEOUT_COMMAND_HDLR HC_HciWrAutoFlushToCmdHdlr_FLASH
#else
#define HCI_WRITE_AUTOMATIC_FLUSH_TIMEOUT_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0029 */
#if (HCI_READ_NUM_BROADCAST_RETRANSMISSIONS_COMMAND_SUPPORTED)
#define HCI_READ_NUM_BROADCAST_RETRANSMISSIONS_COMMAND_HDLR HC_HciRdNumBcRtxCmdHdlr_FLASH
#else
#define HCI_READ_NUM_BROADCAST_RETRANSMISSIONS_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x002A */
#if (HCI_WRITE_NUM_BROADCAST_RETRANSMISSIONS_COMMAND_SUPPORTED)
#define HCI_WRITE_NUM_BROADCAST_RETRANSMISSIONS_COMMAND_HDLR HC_HciWrNumBcRtxCmdHdlr_FLASH
#else
#define HCI_WRITE_NUM_BROADCAST_RETRANSMISSIONS_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x002B */
#if (HCI_READ_HOLD_MODE_ACTIVITY_COMMAND_SUPPORTED)
#define HCI_READ_HOLD_MODE_ACTIVITY_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_READ_HOLD_MODE_ACTIVITY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x002C */
#if (HCI_WRITE_HOLD_MODE_ACTIVITY_COMMAND_SUPPORTED)
#define HCI_WRITE_HOLD_MODE_ACTIVITY_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_WRITE_HOLD_MODE_ACTIVITY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x002D */
#if (HCI_READ_TRANSMIT_POWER_LEVEL_COMMAND_SUPPORTED)
#define HCI_READ_TRANSMIT_POWER_LEVEL_COMMAND_HDLR HC_HciRdTxPwrLvCmdHdlr_FLASH
#else
#define HCI_READ_TRANSMIT_POWER_LEVEL_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x002E */ /* SCO HCI is unsupported */
#if (HCI_READ_SYNCHRONOUS_FLOW_CONTROL_ENABLE_COMMAND_SUPPORTED)
#define HCI_READ_SYNCHRONOUS_FLOW_CONTROL_ENABLE_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_READ_SYNCHRONOUS_FLOW_CONTROL_ENABLE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x002F */ /* SCO HCI is unsupported */
#if (HCI_WRITE_SYNCHRONOUS_FLOW_CONTROL_ENABLE_COMMAND_SUPPORTED)
#define HCI_WRITE_SYNCHRONOUS_FLOW_CONTROL_ENABLE_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_WRITE_SYNCHRONOUS_FLOW_CONTROL_ENABLE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0031 */ /* Host Flow Control is unsupported */
#if (HCI_SET_CONTROLLER_TO_HOST_FLOW_CONTROL_COMMAND_SUPPORTED)
#define HCI_SET_CONTROLLER_TO_HOST_FLOW_CONTROL_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_SET_CONTROLLER_TO_HOST_FLOW_CONTROL_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0033 */ /* Host Flow Control is unsupported */
#if (HCI_HOST_BUFFER_SIZE_COMMAND_SUPPORTED)
#define HCI_HOST_BUFFER_SIZE_COMMAND_HDLR HC_HciHostBufSizeCmdHdlr_FLASH
#else
#define HCI_HOST_BUFFER_SIZE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0035 */ /* Host Flow Control is unsupported */
#if (HCI_HOST_NUMBER_OF_COMPLETED_PACKETS_COMMAND_SUPPORTED)
#define HCI_HOST_NUMBER_OF_COMPLETED_PACKETS_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_HOST_NUMBER_OF_COMPLETED_PACKETS_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0036 */
#if (HCI_READ_LINK_SUPERVISION_TIMEOUT_COMMAND_SUPPORTED)
#define HCI_READ_LINK_SUPERVISION_TIMEOUT_COMMAND_HDLR HC_HciRdLinkSupervisionToCmdHdlr_FLASH
#else
#define HCI_READ_LINK_SUPERVISION_TIMEOUT_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0037 */
#if (HCI_WRITE_LINK_SUPERVISION_TIMEOUT_COMMAND_SUPPORTED)
#define HCI_WRITE_LINK_SUPERVISION_TIMEOUT_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_WRITE_LINK_SUPERVISION_TIMEOUT_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0038 */
#if (HCI_READ_NUMBER_OF_SUPPORTED_IAC_COMMAND_SUPPORTED)
#define HCI_READ_NUMBER_OF_SUPPORTED_IAC_COMMAND_HDLR HC_HciRdNumOfSuppIacCmdHdlr_FLASH
#else
#define HCI_READ_NUMBER_OF_SUPPORTED_IAC_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0039 */
#if (HCI_READ_CURRENT_IAC_LAP_COMMAND_SUPPORTED)
#define HCI_READ_CURRENT_IAC_LAP_COMMAND_HDLR HC_HciRdCurrIacLapCmdHdlr_FLASH
#else
#define HCI_READ_CURRENT_IAC_LAP_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x003A */
#if (HCI_WRITE_CURRENT_IAC_LAP_COMMAND_SUPPORTED)
#define HCI_WRITE_CURRENT_IAC_LAP_COMMAND_HDLR HC_HciWrCurrIacLapCmdHdlr_FLASH
#else
#define HCI_WRITE_CURRENT_IAC_LAP_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x003F */
#if (HCI_SET_AFH_HOST_CHANNEL_CLASSIFICATION_COMMAND_SUPPORTED)
#define HCI_SET_AFH_HOST_CHANNEL_CLASSIFICATION_COMMAND_HDLR HC_HciSetAfhHostChClassificationCmdHdlr_FLASH
#else
#define HCI_SET_AFH_HOST_CHANNEL_CLASSIFICATION_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0042 */
#if (HCI_READ_INQUIRY_SCAN_TYPE_COMMAND_SUPPORTED)
#define HCI_READ_INQUIRY_SCAN_TYPE_COMMAND_HDLR HC_HciRdInqScanTypeCmdHdlr_FLASH
#else
#define HCI_READ_INQUIRY_SCAN_TYPE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0043 */
#if (HCI_WRITE_INQUIRY_SCAN_TYPE_COMMAND_SUPPORTED)
#define HCI_WRITE_INQUIRY_SCAN_TYPE_COMMAND_HDLR HC_HciWrInqScanTypeCmdHdlr_FLASH
#else
#define HCI_WRITE_INQUIRY_SCAN_TYPE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0044 */
#if (HCI_READ_INQUIRY_MODE_COMMAND_SUPPORTED)
#define HCI_READ_INQUIRY_MODE_COMMAND_HDLR HC_HciRdInqModeCmdHdlr_FLASH
#else
#define HCI_READ_INQUIRY_MODE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0045 */
#if (HCI_WRITE_INQUIRY_MODE_COMMAND_SUPPORTED)
#define HCI_WRITE_INQUIRY_MODE_COMMAND_HDLR HC_HciWrInqModeCmdHdlr_FLASH
#else
#define HCI_WRITE_INQUIRY_MODE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0046 */
#if (HCI_READ_PAGE_SCAN_TYPE_COMMAND_SUPPORTED)
#define HCI_READ_PAGE_SCAN_TYPE_COMMAND_HDLR HC_HciRdPageScanTypeCmdHdlr_FLASH
#else
#define HCI_READ_PAGE_SCAN_TYPE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0047 */
#if (HCI_WRITE_PAGE_SCAN_TYPE_COMMAND_SUPPORTED)
#define HCI_WRITE_PAGE_SCAN_TYPE_COMMAND_HDLR HC_HciWrPageScanTypeCmdHdlr_FLASH
#else
#define HCI_WRITE_PAGE_SCAN_TYPE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0048 */
#if (HCI_READ_AFH_CHANNEL_ASSESSMENT_MODE_COMMAND_SUPPORTED)
#define HCI_READ_AFH_CHANNEL_ASSESSMENT_MODE_COMMAND_HDLR HC_HciRdAfhChAssessModeCmdHdlr_FLASH
#else
#define HCI_READ_AFH_CHANNEL_ASSESSMENT_MODE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0049 */
#if (HCI_WRITE_AFH_CHANNEL_ASSESSMENT_MODE_COMMAND_SUPPORTED)
#define HCI_WRITE_AFH_CHANNEL_ASSESSMENT_MODE_COMMAND_HDLR HC_HciWrAfhChAssessModeCmdHdlr_FLASH
#else
#define HCI_WRITE_AFH_CHANNEL_ASSESSMENT_MODE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0051 */
#if (HCI_READ_EXTENDED_INQUIRY_RESPONSE_COMMAND_SUPPORTED)
#define HCI_READ_EXTENDED_INQUIRY_RESPONSE_COMMAND_HDLR HC_HciRdEirCmdHdlr_FLASH
#else
#define HCI_READ_EXTENDED_INQUIRY_RESPONSE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0052 */
#if (HCI_WRITE_EXTENDED_INQUIRY_RESPONSE_COMMAND_SUPPORTED)
#define HCI_WRITE_EXTENDED_INQUIRY_RESPONSE_COMMAND_HDLR HC_HciWrEirCmdHdlr_FLASH
#else
#define HCI_WRITE_EXTENDED_INQUIRY_RESPONSE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0053 */
#if (HCI_REFRESH_ENCRYPTION_KEY_COMMAND_SUPPORTED)
#define HCI_REFRESH_ENCRYPTION_KEY_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_REFRESH_ENCRYPTION_KEY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0055 */
#if (HCI_READ_SIMPLE_PAIRING_MODE_COMMAND_SUPPORTED)
#define HCI_READ_SIMPLE_PAIRING_MODE_COMMAND_HDLR HC_HciRdSimplePairingModeCmdHdlr_FLASH
#else
#define HCI_READ_SIMPLE_PAIRING_MODE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0056 */
#if (HCI_WRITE_SIMPLE_PAIRING_MODE_COMMAND_SUPPORTED)
#define HCI_WRITE_SIMPLE_PAIRING_MODE_COMMAND_HDLR HC_HciWrSimplePairingModeCmdHdlr_FLASH
#else
#define HCI_WRITE_SIMPLE_PAIRING_MODE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0057 */
#if (HCI_READ_LOCAL_OOB_DATA_COMMAND_SUPPORTED)
#define HCI_READ_LOCAL_OOB_DATA_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_READ_LOCAL_OOB_DATA_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0058 */
#if (HCI_READ_INQUIRY_RESPONSE_TRANSMIT_POWER_LEVEL_COMMAND_SUPPORTED)
#define HCI_READ_INQUIRY_RESPONSE_TRANSMIT_POWER_LEVEL_COMMAND_HDLR HC_HciRdInqRspTxPwrLvCmdHdlr_FLASH
#else
#define HCI_READ_INQUIRY_RESPONSE_TRANSMIT_POWER_LEVEL_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0059 */
#if (HCI_WRITE_INQUIRY_TRANSMIT_POWER_LEVEL_COMMAND_SUPPORTED)
#define HCI_WRITE_INQUIRY_TRANSMIT_POWER_LEVEL_COMMAND_HDLR HC_HciWrInqTxPwrLvCmdHdlr_FLASH
#else
#define HCI_WRITE_INQUIRY_TRANSMIT_POWER_LEVEL_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x005A */ /* Erroneous Report is unsupported */
#if (HCI_READ_DEFAULT_ERRONEOUS_DATA_REPORTING_COMMAND_SUPPORTED)
#define HCI_READ_DEFAULT_ERRONEOUS_DATA_REPORTING_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_READ_DEFAULT_ERRONEOUS_DATA_REPORTING_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x005B */ /* Erroneous Report is unsupported */
#if (HCI_WRITE_DEFAULT_ERRONEOUS_DATA_REPORTING_COMMAND_SUPPORTED)
#define HCI_WRITE_DEFAULT_ERRONEOUS_DATA_REPORTING_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_WRITE_DEFAULT_ERRONEOUS_DATA_REPORTING_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x005F */
#if (HCI_ENHANCED_FLUSH_COMMAND_SUPPORTED)
#define HCI_ENHANCED_FLUSH_COMMAND_HDLR HC_HciEnhancedFlushCmdHdlr_FLASH
#else
#define HCI_ENHANCED_FLUSH_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0060 */
#if (HCI_SEND_KEYPRESS_NOTIFICATION_COMMAND_SUPPORTED)
#define HCI_SEND_KEYPRESS_NOTIFICATION_COMMAND_HDLR HC_HciCmdRelayToLm
#else
#define HCI_SEND_KEYPRESS_NOTIFICATION_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0060 */
#if (HCI_READ_ENHANCED_TRANSMIT_POWER_LEVEL_COMMAND_SUPPORTED)
#define HCI_READ_ENHANCED_TRANSMIT_POWER_LEVEL_COMMAND_HDLR HC_HciRdEnhancedTxPwrLvCmdHdlr_FLASH
#else
#define HCI_READ_ENHANCED_TRANSMIT_POWER_LEVEL_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x006C */
#if (HCI_READ_LE_HOST_SUPPORT_COMMAND_SUPPORTED)
#define HCI_READ_LE_HOST_SUPPORT_COMMAND_HDLR HC_HciRdLeHostSuppCmdHdlr
#else
#define HCI_READ_LE_HOST_SUPPORT_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x006D */
#if (HCI_WRITE_LE_HOST_SUPPORT_COMMAND_SUPPORTED)
#define HCI_WRITE_LE_HOST_SUPPORT_COMMAND_HDLR HC_HciWrLeHostSuppCmdHdlr
#else
#define HCI_WRITE_LE_HOST_SUPPORT_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif



////////////////////////////////////////////////////////////////////////////////
// OGF : 0x04 Informational Parameters /////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
/* OCF : 0x0001 */
#if (HCI_READ_LOCAL_VERSION_INFORMATION_COMMAND_SUPPORTED)
#define HCI_READ_LOCAL_VERSION_INFORMATION_COMMAND_HDLR HC_HciRdLocalVerInfoCmdHdlr
#else
#define HCI_READ_LOCAL_VERSION_INFORMATION_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0003 */
#if (HCI_READ_LOCAL_SUPPORTED_FEATURES_COMMAND_SUPPORTED)
#define HCI_READ_LOCAL_SUPPORTED_FEATURES_COMMAND_HDLR HC_HciRdLocalSuppFeaCmdHdlr
#else
#define HCI_READ_LOCAL_SUPPORTED_FEATURES_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0004 */
#if (HCI_READ_LOCAL_EXTENDED_FEATURES_COMMAND_SUPPORTED)
#define HCI_READ_LOCAL_EXTENDED_FEATURES_COMMAND_HDLR HC_HciRdLocalExtnFeaCmdHdlr_FLASH
#else
#define HCI_READ_LOCAL_EXTENDED_FEATURES_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0005 */
#if (HCI_READ_BUFFER_SIZE_COMMAND_SUPPORTED)
#define HCI_READ_BUFFER_SIZE_COMMAND_HDLR HC_HciRdBufSizeCmdHdlr
#else
#define HCI_READ_BUFFER_SIZE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0009 */
#if (HCI_READ_BD_ADDR_COMMAND_SUPPORTED)
#define HCI_READ_BD_ADDR_COMMAND_HDLR HC_HciRdBdAddrCmdHdlr
#else
#define HCI_READ_BD_ADDR_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x000A */
#if (HCI_READ_DATA_BLOCK_SIZE_COMMAND_SUPPORTED)
#define HCI_READ_DATA_BLOCK_SIZE_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_READ_DATA_BLOCK_SIZE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x000B */
#if (HCI_READ_LOCAL_SUPPORTED_CODECS_COMMAND_SUPPORTED)
#define HCI_READ_LOCAL_SUPPORTED_CODECS_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_READ_LOCAL_SUPPORTED_CODECS_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif



////////////////////////////////////////////////////////////////////////////////
// OGF : 0x05 Status Parameters ////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
/* OCF : 0x0001 */
#if (HCI_READ_FAILED_CONTACT_COUNTER_COMMAND_SUPPORTED)
#define HCI_READ_FAILED_CONTACT_COUNTER_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_READ_FAILED_CONTACT_COUNTER_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0002 */
#if (HCI_RESET_FAILED_CONTACT_COUNTER_COMMAND_SUPPORTED)
#define HCI_RESET_FAILED_CONTACT_COUNTER_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_RESET_FAILED_CONTACT_COUNTER_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0003 */
#if (HCI_READ_LINK_QUALITY_COMMAND_SUPPORTED)
#define HCI_READ_LINK_QUALITY_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_READ_LINK_QUALITY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0005 */
#if (HCI_READ_RSSI_COMMAND_SUPPORTED)
#define HCI_READ_RSSI_COMMAND_HDLR HC_HciRdRssiCmdHdlr_FLASH
#else
#define HCI_READ_RSSI_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0006 */
#if (HCI_READ_AFH_CHANNEL_MAP_COMMAND_SUPPORTED)
#define HCI_READ_AFH_CHANNEL_MAP_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_READ_AFH_CHANNEL_MAP_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0007 */
#if (HCI_READ_CLOCK_COMMAND_SUPPORTED)
#define HCI_READ_CLOCK_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_READ_CLOCK_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0008 */
#if (HCI_READ_ENCRYPTION_KEY_SIZE_COMMAND_SUPPORTED)
#define HCI_READ_ENCRYPTION_KEY_SIZE_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_READ_ENCRYPTION_KEY_SIZE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif



////////////////////////////////////////////////////////////////////////////////
// OGF : 0x06 Testing //////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
/* OCF : 0x0001 */
#if (HCI_READ_LOOPBACK_MODE_COMMAND_SUPPORTED)
#define HCI_READ_LOOPBACK_MODE_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_READ_LOOPBACK_MODE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0002 */
#if (HCI_WRITE_LOOPBACK_MODE_COMMAND_SUPPORTED)
#define HCI_WRITE_LOOPBACK_MODE_COMMAND_HDLR HC_HciRejectCmdHdlr
#else
#define HCI_WRITE_LOOPBACK_MODE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0003 */
#if (HCI_ENABLE_DEVICE_UNDER_TEST_MODE_COMMAND_SUPPORTED)
#define HCI_ENABLE_DEVICE_UNDER_TEST_MODE_COMMAND_HDLR HC_HciEnableDeviceUnderTestModeCmdHdlr_FLASH
#else
#define HCI_ENABLE_DEVICE_UNDER_TEST_MODE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0004 */
#if (HCI_WRITE_SIMPLE_PAIRING_DEBUG_MODE_COMMAND_SUPPORTED)
#define HCI_WRITE_SIMPLE_PAIRING_DEBUG_MODE_COMMAND_HDLR HC_HciWrSimplePairingDbgModeCmdHdlr_FLASH
#else
#define HCI_WRITE_SIMPLE_PAIRING_DEBUG_MODE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif



////////////////////////////////////////////////////////////////////////////////
// OGF : 0x08 LE Controller Commands ///////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
/* OCF : 0x0001 */
#if (HCI_LE_SET_EVENT_MASK_COMMAND_SUPPORTED)
#define HCI_LE_SET_EVENT_MASK_COMMAND_HDLR HC_HciLeSetEvtMaskCmdHdlr
#else
#define HCI_LE_SET_EVENT_MASK_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0002 */
#if (HCI_LE_READ_BUFFER_SIZE_COMMAND_SUPPORTED)
#define HCI_LE_READ_BUFFER_SIZE_COMMAND_HDLR HC_HciLeRdBufSizeCmdHdlr
#else
#define HCI_LE_READ_BUFFER_SIZE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0004 */
#if (HCI_LE_READ_LOCAL_SUPPORTED_FEATURES_COMMAND_SUPPORTED)
#define HCI_LE_READ_LOCAL_SUPPORTED_FEATURES_COMMAND_HDLR HC_HciLeRdLocalSuppFeaCmdHdlr
#else
#define HCI_LE_READ_LOCAL_SUPPORTED_FEATURES_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0005 */
#if (HCI_LE_SET_RANDOM_ADDRESS_COMMAND_SUPPORTED)
#define HCI_LE_SET_RANDOM_ADDRESS_COMMAND_HDLR HC_HciLeSetRandAddrCmdHdlr
#else
#define HCI_LE_SET_RANDOM_ADDRESS_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0006 */
#if (HCI_LE_SET_ADVERTISING_PARAMETERS_COMMAND_SUPPORTED)
#define HCI_LE_SET_ADVERTISING_PARAMETERS_COMMAND_HDLR HC_HciCmdRelayToLL
#else
#define HCI_LE_SET_ADVERTISING_PARAMETERS_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0007 */
#if (HCI_LE_READ_ADVERTISING_CHANNEL_TX_POWER_COMMAND_SUPPORTED)
#define HCI_LE_READ_ADVERTISING_CHANNEL_TX_POWER_COMMAND_HDLR HC_HciLeRdAdvChTxPwrCmdHdlr
#else
#define HCI_LE_READ_ADVERTISING_CHANNEL_TX_POWER_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0008 */
#if (HCI_LE_SET_ADVERTISING_DATA_COMMAND_SUPPORTED)
#define HCI_LE_SET_ADVERTISING_DATA_COMMAND_HDLR HC_HciCmdRelayToLL
#else
#define HCI_LE_SET_ADVERTISING_DATA_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0009 */
#if (HCI_LE_SET_SCAN_RESPONSE_DATA_COMMAND_SUPPORTED)
#define HCI_LE_SET_SCAN_RESPONSE_DATA_COMMAND_HDLR HC_HciCmdRelayToLL
#else
#define HCI_LE_SET_SCAN_RESPONSE_DATA_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x000A */
#if (HCI_LE_SET_ADVERTISE_ENABLE_COMMAND_SUPPORTED)
#define HCI_LE_SET_ADVERTISE_ENABLE_COMMAND_HDLR HC_HciCmdRelayToLL
#else
#define HCI_LE_SET_ADVERTISE_ENABLE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x000B */
#if (HCI_LE_SET_SCAN_PARAMETERS_COMMAND_SUPPORTED)
#define HCI_LE_SET_SCAN_PARAMETERS_COMMAND_HDLR HC_HciCmdRelayToLL
#else
#define HCI_LE_SET_SCAN_PARAMETERS_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x000C */
#if (HCI_LE_SET_SCAN_ENABLE_COMMAND_SUPPORTED)
#define HCI_LE_SET_SCAN_ENABLE_COMMAND_HDLR HC_HciCmdRelayToLL
#else
#define HCI_LE_SET_SCAN_ENABLE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x000D */
#if (HCI_LE_CREATE_CONNECTION_COMMAND_SUPPORTED)
#define HCI_LE_CREATE_CONNECTION_COMMAND_HDLR HC_HciCmdRelayToLL
#else
#define HCI_LE_CREATE_CONNECTION_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x000E */
#if (HCI_LE_CREATE_CONNECTION_CANCEL_COMMAND_SUPPORTED)
#define HCI_LE_CREATE_CONNECTION_CANCEL_COMMAND_HDLR HC_HciCmdRelayToLL
#else
#define HCI_LE_CREATE_CONNECTION_CANCEL_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x000F */
#if (HCI_LE_READ_WHITE_LIST_SIZE_COMMAND_SUPPORTED)
#define HCI_LE_READ_WHITE_LIST_SIZE_COMMAND_HDLR HC_HciLeRdWhiteListSizeCmdHdlr
#else
#define HCI_LE_READ_WHITE_LIST_SIZE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0010 */
#if (HCI_LE_CLEAR_WHITE_LIST_COMMAND_SUPPORTED)
#define HCI_LE_CLEAR_WHITE_LIST_COMMAND_HDLR HC_HciLeClrWhiteListCmdHdlr
#else
#define HCI_LE_CLEAR_WHITE_LIST_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0011 */
#if (HCI_LE_ADD_DEVICE_TO_WHITE_LIST_COMMAND_SUPPORTED)
#define HCI_LE_ADD_DEVICE_TO_WHITE_LIST_COMMAND_HDLR HC_HciLeAddDeviceToWhiteListCmdHdlr
#else
#define HCI_LE_ADD_DEVICE_TO_WHITE_LIST_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0012 */
#if (HCI_LE_REMOVE_DEVICE_FROM_WHITE_LIST_COMMAND_SUPPORTED)
#define HCI_LE_REMOVE_DEVICE_FROM_WHITE_LIST_COMMAND_HDLR HC_HciLeRmDeviceFromWhiteListCmdHdlr
#else
#define HCI_LE_REMOVE_DEVICE_FROM_WHITE_LIST_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0013 */
#if (HCI_LE_CONNECTION_UPDATE_COMMAND_SUPPORTED)
#define HCI_LE_CONNECTION_UPDATE_COMMAND_HDLR HC_HciCmdRelayToLL_ByCH
#else
#define HCI_LE_CONNECTION_UPDATE_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0014 */
#if (HCI_LE_SET_HOST_CHANNEL_CLASSIFICATION_COMMAND_SUPPORTED)
#define HCI_LE_SET_HOST_CHANNEL_CLASSIFICATION_COMMAND_HDLR HC_HciCmdRelayToLL
#else
#define HCI_LE_SET_HOST_CHANNEL_CLASSIFICATION_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0015 */
#if (HCI_LE_READ_CHANNEL_MAP_COMMAND_SUPPORTED)
#define HCI_LE_READ_CHANNEL_MAP_COMMAND_HDLR HC_HciCmdRelayToLL_ByCH
#else
#define HCI_LE_READ_CHANNEL_MAP_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0016 */
#if (HCI_LE_READ_REMOTE_USED_FEATURES_COMMAND_SUPPORTED)
#define HCI_LE_READ_REMOTE_USED_FEATURES_COMMAND_HDLR HC_HciCmdRelayToLL_ByCH
#else
#define HCI_LE_READ_REMOTE_USED_FEATURES_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0017 */
#if (HCI_LE_ENCRYPT_COMMAND_SUPPORTED)
#define HCI_LE_ENCRYPT_COMMAND_HDLR HC_HciCmdRelayToLL
#else
#define HCI_LE_ENCRYPT_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0018 */
#if (HCI_LE_RAND_COMMAND_SUPPORTED)
#define HCI_LE_RAND_COMMAND_HDLR HC_HciLeRandCmdHdlr
#else
#define HCI_LE_RAND_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0019 */
#if (HCI_LE_START_ENCRYPTION_COMMAND_SUPPORTED)
#define HCI_LE_START_ENCRYPTION_COMMAND_HDLR HC_HciCmdRelayToLL_ByCH
#else
#define HCI_LE_START_ENCRYPTION_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x001A */
#if (HCI_LE_LONG_TERM_KEY_REQUEST_REPLY_COMMAND_SUPPORTED)
#define HCI_LE_LONG_TERM_KEY_REQUEST_REPLY_COMMAND_HDLR HC_HciCmdRelayToLL_ByCH
#else
#define HCI_LE_LONG_TERM_KEY_REQUEST_REPLY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x001B */
#if (HCI_LE_LONG_TERM_KEY_REQUEST_NEGATIVE_REPLY_COMMAND_SUPPORTED)
#define HCI_LE_LONG_TERM_KEY_REQUEST_NEGATIVE_REPLY_COMMAND_HDLR HC_HciCmdRelayToLL_ByCH
#else
#define HCI_LE_LONG_TERM_KEY_REQUEST_NEGATIVE_REPLY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x001C */
#if (HCI_LE_READ_SUPPORTED_STATES_COMMAND_SUPPORTED)
#define HCI_LE_READ_SUPPORTED_STATES_COMMAND_HDLR HC_HciLeRdSuppStateCmdHdlr
#else
#define HCI_LE_READ_SUPPORTED_STATES_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x001D */
#if (HCI_LE_RECEIVER_TEST_COMMAND_SUPPORTED)
#define HCI_LE_RECEIVER_TEST_COMMAND_HDLR HC_HciCmdRelayToLL
#else
#define HCI_LE_RECEIVER_TEST_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x001E */
#if (HCI_LE_TRANSMITTER_TEST_COMMAND_SUPPORTED)
#define HCI_LE_TRANSMITTER_TEST_COMMAND_HDLR HC_HciCmdRelayToLL
#else
#define HCI_LE_TRANSMITTER_TEST_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x001F */
#if (HCI_LE_TEST_END_COMMAND_SUPPORTED)
#define HCI_LE_TEST_END_COMMAND_HDLR HC_HciCmdRelayToLL
#else
#define HCI_LE_TEST_END_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0020 */
#if (HCI_LE_REMOTE_CONNECTION_PARAMETER_REQUEST_REPLY_COMMAND_SUPPORTED)
#define HCI_LE_REMOTE_CONNECTION_PARAMETER_REQUEST_REPLY_COMMAND_HDLR HC_HciCmdRelayToLL_ByCH
#else
#define HCI_LE_REMOTE_CONNECTION_PARAMETER_REQUEST_REPLY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0021 */
#if (HCI_LE_REMOTE_CONNECTION_PARAMETER_REQUEST_NEGATIVE_REPLY_COMMAND_SUPPORTED)
#define HCI_LE_REMOTE_CONNECTION_PARAMETER_REQUEST_NEGATIVE_REPLY_COMMAND_HDLR HC_HciCmdRelayToLL_ByCH
#else
#define HCI_LE_REMOTE_CONNECTION_PARAMETER_REQUEST_NEGATIVE_REPLY_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0022 */
#if (HCI_LE_SET_DATA_LENGTH_COMMAND_SUPPORTED)
#define HCI_LE_SET_DATA_LENGTH_COMMAND_HDLR HC_HciCmdRelayToLL_ByCH
#else
#define HCI_LE_SET_DATA_LENGTH_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0023 */
#if (HCI_LE_READ_SUGGESTED_DEFAULT_DATA_LENGTH_COMMAND_SUPPORTED)
#define HCI_LE_READ_SUGGESTED_DEFAULT_DATA_LENGTH_COMMAND_HDLR HC_HciCmdRelayToLL
#else
#define HCI_LE_READ_SUGGESTED_DEFAULT_DATA_LENGTH_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif

/* OCF : 0x0024 */
#if (HCI_LE_WRITE_SUGGESTED_DEFAULT_DATA_LENGTH_COMMAND_SUPPORTED)
#define HCI_LE_WRITE_SUGGESTED_DEFAULT_DATA_LENGTH_COMMAND_HDLR HC_HciCmdRelayToLL
#else
#define HCI_LE_WRITE_SUGGESTED_DEFAULT_DATA_LENGTH_COMMAND_HDLR HC_HciRejectCmdHdlr
#endif


#endif /* _HC_CMD_HDLR_FLASH_H_ */


