
// HCI_VEVT_OCF_L2CAP_DBGPRINT_ROM_INIT = {"L2C - L2C_ROM Init"};
// HCI_VEVT_OCF_L2CAP_DBGPRINT_ROM_DROP_PACKET = {"L2C - Drop One L2CAP PKT"}
// HCI_VEVT_OCF_L2CAP_DBGPRINT_ROM_RECOMBINE = {"L2C - Recomb Same mem_ptr"}
// HCI_VEVT_OCF_L2CAP_DBGPRINT_ROM_DIFF_MEM_PTR {"L2C - Recomb Diff mem_ptr"}
// HCI_VEVT_OCF_L2CAP_DBGPRINT_ROM_SEG3 = {"L2C - L2C seg3: %d ", (U8)length}
// HCI_VEVT_OCF_L2CAP_DBGPRINT_ROM_ATT_DATA = {"L2C - ATT_data"}



// HCI_VEVT_OCF_MMI_LE_DBGPRINT_ROM_INIT = {"MMI - MMI_LE_ROM Init"}
// HCI_VEVT_OCF_MMI_LE_DBGPRINT_ERROR_STATE = {"MMI - MMI_LE_ROM Err State"}
// HCI_VEVT_OCF_MMI_LE_DBGPRINT_ERROR_SUBSTATE = {"MMI - MMI_LE Err Substate"}
// HCI_VEVT_OCF_MMI_LE_DBGPRINT_ENABLE_ADV = {"MMI - LE Enable Adv"}
// HCI_VEVT_OCF_MMI_LE_DBGPRINT_GET_META = {"MMI - MMI_LE_Get_META!"}
// HCI_VEVT_OCF_MMI_LE_DBGPRINT_CONN_FAIL = {"MMI - LE connection fail"}
// HCI_VEVT_OCF_MMI_LE_DBGPRINT_CONN_CPL = {"MMI - LE META -conn complete"}
// HCI_VEVT_OCF_MMI_LE_DBGPRINT_UNEXPECTED_EVT = {"MMI - LE unexpected evt"}
// HCI_VEVT_OCF_MMI_LE_DBGPRINT_GET_EVT = {"USR - Get event: %d %d ", (U8)mq_ptr[3], (U8)mq_ptr[6]}
// HCI_VEVT_OCF_MMI_LE_DBGPRINT_AUTO_OFF = {"USR - Auto Shutdown!"}
// HCI_VEVT_OCF_MMI_LE_DBGPRINT_KEY_PRESS = {("DRV - KeyPress: %d", (U8)(U8)gMMI_le_rom_ctl.KeyPressTimerType[timerInd], (U8)timerInd}




// HCI_VEVT_OCF_GAP_DBGPRINT_LE_DISC = {"GAP - GAP_ROM Get LE Disc !!"}
// HCI_VEVT_OCF_GAP_DBGPRINT_LE_GET_META = {"GAP - GAP_ROM Get LE META !!"}
// HCI_VEVT_OCF_GAP_DBGPRINT_LE_DISCARD_NON_LE = {"GAP - Discard non LE CMD"}
// HCI_VEVT_OCF_GAP_DBGPRINT_LE_ADV_ENABLE = {"USR - GAP_ROM_ADV_ENABLE"}
// HCI_VEVT_OCF_GAP_DBGPRINT_LE_CMD_ERROR = {"GAP-COMMAND_STATUS_ERR:%d", *(ptr1 + GAP_EVENT_PARA0_OFFSET)}
// HCI_VEVT_OCF_GAP_DBGPRINT_LE_CMD_CPL = {"USR - GAP CMD complete"}