#ifndef _BT_CONFIG_H_
#define _BT_CONFIG_H_
/*
 * AIROHA Bluetooth Device Firmware
 * COPYRIGHT (C) 2014 AIROHA TECHNOLOGY CORP. CO., LTD. ALL RIGHTS RESERVED
 *
 * bt_config.h define Bluetooth command configuration
 *
 * Programmer : CharlesSu@airoha.com.tw, Ext.2882
 */
#include "boolean.h"
#include "ctlr_config.h"



/**
 * Configuration to HCI Supported Commands
 */
// Octet 0
#define HCI_INQUIRY_COMMAND_SUPPORTED                                           (TRUE  && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_INQUIRY_CANCEL_COMMAND_SUPPORTED                                    (TRUE  && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_PERIODIC_INQUIRY_MODE_COMMAND_SUPPORTED                             (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_EXIT_PERIODIC_INQUIRY_MODE_COMMAND_SUPPORTED                        (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_CREATE_CONNECTION_COMMAND_SUPPOTRED                                 (TRUE  && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_DISCONNECT_COMMAND_SUPPORTED                                        (TRUE  && (BR_EDR_SUPPORTED_CONTROLLER || LE_SUPPORTED_CONTROLLER))
#define HCI_ADD_SCO_CONNECTION_COMMAND_SUPPORTED                                (FALSE && BR_EDR_SUPPORTED_CONTROLLER) /* Deprecated */
#define HCI_CREATE_CONNECTION_CANCEL_COMMAND_SUPPORTED                          (TRUE  && BR_EDR_SUPPORTED_CONTROLLER)
// Octet 1
#define HCI_ACCEPT_CONNECTION_REQUEST_COMMAND_SUPPORTED                         (TRUE  && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_REJECT_CONNECTION_REQUEST_COMMAND_SUPPORTED                         (TRUE  && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_LINK_KEY_REQUEST_REPLY_COMMAND_SUPPORTED                            (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_LINK_KEY_REQUEST_NEGATIVE_REPLY_COMMAND_SUPPORTED                   (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_PIN_CODE_REQUEST_REPLY_COMMAND_SUPPORTED                            (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_PIN_CODE_REQUEST_NEGATIVE_REPLY_COMMAND_SUPPORTED                   (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_CHANGE_CONNECTION_PACKET_TYPE_COMMAND_SUPPORTED                     (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_AUTHENTICATION_REQUEST_COMMAND_SUPPORTED                            (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
// Octet 2
#define HCI_SET_CONNECTION_ENCRYPTION_COMMAND_SUPPORTED                         (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_CHANGE_CONNECTION_LINK_KEY_COMMAND_SUPPORTED                        (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_MASTER_LINK_KEY_COMMAND_SUPPORTED                                   (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_REMOTE_NAME_REQUEST_COMMAND_SUPPORTED                               (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_REMOTE_NAME_REQUEST_CANCEL_COMMAND_SUPPORTED                        (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_REMOTE_SUPPORTED_FEATURES_COMMAND_SUPPORTED                    (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_REMOTE_EXTENDED_FEATURES_COMMAND_SUPPORTED                     (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_REMOTE_VERSION_INFORMATION_COMMAND_SUPPORTED                   (TRUE  && (BR_EDR_SUPPORTED_CONTROLLER || LE_SUPPORTED_CONTROLLER))
// Octet 3
#define HCI_READ_CLOCK_OFFSET_COMMAND_SUPPORTED                                 (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_LMP_HANDLE_COMMAND_SUPPORTED                                   (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
// Octet 4
#define HCI_HOLD_MODE_COMMAND_SUPPORTED                                         (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_SNIFF_MODE_COMMAND_SUPPORTED                                        (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_EXIT_SNIFF_MODE_COMMAND_SUPPORTED                                   (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_PARK_STATE_COMMAND_SUPPORTED                                        (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_EXIT_PARK_STATE_COMMAND_SUPPORTED                                   (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_QOS_SETUP_COMMAND_SUPPORTED                                         (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_ROLE_DISCOVERY_COMMAND_SUPPORTED                                    (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
// Octet 5
#define HCI_SWITCH_ROLE_COMMAND_SUPPORTED                                       (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_LINK_POLICY_SETTINGS_COMMAND_SUPPORTED                         (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_WRITE_LINK_POLICY_SETTINGS_COMMAND_SUPPORTED                        (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_DEFAULT_LINK_POLICY_SETTINGS_COMMAND_SUPPORTED                 (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_WRITE_DEFAULT_LINK_POLICY_SETTINGS_COMMAND_SUPPORTED                (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_FLOW_SPECIFICATION_COMMAND_SUPPORTED                                (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_SET_EVENT_MASK_COMMAND_SUPPORTED                                    (TRUE  && (BR_EDR_SUPPORTED_CONTROLLER || LE_SUPPORTED_CONTROLLER))
#define HCI_RESET_COMMAND_SUPPORTED                                             (TRUE  && (BR_EDR_SUPPORTED_CONTROLLER || LE_SUPPORTED_CONTROLLER))
// Octet 6
#define HCI_SET_EVENT_FILTER_COMMAND_SUPPORTED                                  (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_FLUSH_COMMAND_SUPPORTED                                             (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_PIN_TYPE_COMMAND_SUPPORTED                                     (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_WRITE_PIN_TYPE_COMMAND_SUPPORTED                                    (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_CREATE_NEW_UNIT_KEY_COMMAND_SUPPORTED                               (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_STORED_LINK_KEY_COMMAND_SUPPORTED                              (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_WRITE_STORED_LINK_KEY_COMMAND_SUPPORTED                             (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_DELETE_STORED_LINK_KEY_COMMAND_SUPPORTED                            (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
// Octet 7
#define HCI_WRITE_LOCAL_NAME_COMMAND_SUPPORTED                                  (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_LOCAL_NAME_COMMAND_SUPPORTED                                   (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_CONNECTION_ACCEPT_TIMEOUT_COMMAND_SUPPORTED                    (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_WRITE_CONNECTION_ACCEPT_TIMEOUT_COMMAND_SUPPORTED                   (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_PAGE_TIMEOUT_COMMAND_SUPPORTED                                 (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_WRITE_PAGE_TIMEOUT_COMMAND_SUPPORTED                                (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_SCAN_ENABLE_COMMAND_SUPPORTED                                  (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_WRITE_SCAN_ENABLE_COMMAND_SUPPORTED                                 (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
// Octet 8
#define HCI_READ_PAGE_SCAN_ACTIVITY_COMMAND_SUPPORTED                           (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_WRITE_PAGE_SCAN_ACTIVITY_COMMAND_SUPPORTED                          (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_INQUIRY_SCAN_ACTIVITY_COMMAND_SUPPORTED                        (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_WRITE_INQUIRY_SCAN_ACTIVITY_COMMAND_SUPPORTED                       (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_AUTHENTICATION_ENABLE_COMMAND_SUPPORTED                        (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_WRITE_AUTHENTICATION_ENABLE_COMMAND_SUPPORTED                       (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_ENCRYPTION_MODE_COMMAND_SUPPORTED                              (FALSE && BR_EDR_SUPPORTED_CONTROLLER) /* Deprecated */
#define HCI_WRITE_ENCRYPTION_MODE_COMMAND_SUPPORTED                             (FALSE && BR_EDR_SUPPORTED_CONTROLLER) /* Deprecated */
// Octet 9
#define HCI_READ_CLASS_OF_DEVICE_COMMAND_SUPPORTED                              (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_WRITE_CLASS_OF_DEVICE_COMMAND_SUPPORTED                             (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_VOICE_SETTING_COMMAND_SUPPORTED                                (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_WRITE_VOICE_SETTING_COMMAND_SUPPORTED                               (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_AUTOMATIC_FLUSH_TIMEOUT_COMMAND_SUPPORTED                      (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_WRITE_AUTOMATIC_FLUSH_TIMEOUT_COMMAND_SUPPORTED                     (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_NUM_BROADCAST_RETRANSMISSIONS_COMMAND_SUPPORTED                (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_WRITE_NUM_BROADCAST_RETRANSMISSIONS_COMMAND_SUPPORTED               (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
// Octet 10
#define HCI_READ_HOLD_MODE_ACTIVITY_COMMAND_SUPPORTED                           (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_WRITE_HOLD_MODE_ACTIVITY_COMMAND_SUPPORTED                          (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_TRANSMIT_POWER_LEVEL_COMMAND_SUPPORTED                         (TRUE  && (BR_EDR_SUPPORTED_CONTROLLER || LE_SUPPORTED_CONTROLLER))
#define HCI_READ_SYNCHRONOUS_FLOW_CONTROL_ENABLE_COMMAND_SUPPORTED              (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_WRITE_SYNCHRONOUS_FLOW_CONTROL_ENABLE_COMMAND_SUPPORTED             (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_SET_CONTROLLER_TO_HOST_FLOW_CONTROL_COMMAND_SUPPORTED               (TRUE  && (BR_EDR_SUPPORTED_CONTROLLER || LE_SUPPORTED_CONTROLLER))
#define HCI_HOST_BUFFER_SIZE_COMMAND_SUPPORTED                                  (TRUE  && (BR_EDR_SUPPORTED_CONTROLLER || LE_SUPPORTED_CONTROLLER))
#define HCI_HOST_NUMBER_OF_COMPLETED_PACKETS_COMMAND_SUPPORTED                  (TRUE  && (BR_EDR_SUPPORTED_CONTROLLER || LE_SUPPORTED_CONTROLLER))
// Octet 11
#define HCI_READ_LINK_SUPERVISION_TIMEOUT_COMMAND_SUPPORTED                     (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_WRITE_LINK_SUPERVISION_TIMEOUT_COMMAND_SUPPORTED                    (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_NUMBER_OF_SUPPORTED_IAC_COMMAND_SUPPORTED                      (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_CURRENT_IAC_LAP_COMMAND_SUPPORTED                              (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_WRITE_CURRENT_IAC_LAP_COMMAND_SUPPORTED                             (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_PAGE_SCAN_MODE_PERIOD_COMMAND_SUPPORTED                        (FALSE && BR_EDR_SUPPORTED_CONTROLLER) /* Deprecated */
#define HCI_WRITE_PAGE_SCAN_MODE_PERIOD_COMMAND_SUPPORTED                       (FALSE && BR_EDR_SUPPORTED_CONTROLLER) /* Deprecated */
#define HCI_READ_PAGE_SCAN_MODE_COMMAND_SUPPORTED                               (FALSE && BR_EDR_SUPPORTED_CONTROLLER) /* Deprecated */
// Octet 12
#define HCI_WRITE_PAGE_SCAN_MODE_COMMAND_SUPPORTED                              (FALSE && BR_EDR_SUPPORTED_CONTROLLER) /* Deprecated */
#define HCI_SET_AFH_HOST_CHANNEL_CLASSIFICATION_COMMAND_SUPPORTED               (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_INQUIRY_SCAN_TYPE_COMMAND_SUPPORTED                            (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_WRITE_INQUIRY_SCAN_TYPE_COMMAND_SUPPORTED                           (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_INQUIRY_MODE_COMMAND_SUPPORTED                                 (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_WRITE_INQUIRY_MODE_COMMAND_SUPPORTED                                (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
// Octet 13
#define HCI_READ_PAGE_SCAN_TYPE_COMMAND_SUPPORTED                               (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_WRITE_PAGE_SCAN_TYPE_COMMAND_SUPPORTED                              (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_AFH_CHANNEL_ASSESSMENT_MODE_COMMAND_SUPPORTED                  (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_WRITE_AFH_CHANNEL_ASSESSMENT_MODE_COMMAND_SUPPORTED                 (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
// Octet 14
#define HCI_READ_LOCAL_VERSION_INFORMATION_COMMAND_SUPPORTED                    (TRUE  && (BR_EDR_SUPPORTED_CONTROLLER || LE_SUPPORTED_CONTROLLER))
#define HCI_READ_LOCAL_SUPPORTED_FEATURES_COMMAND_SUPPORTED                     (TRUE  && (BR_EDR_SUPPORTED_CONTROLLER || DUAL_SUPPORTED_CONTROLLER))
#define HCI_READ_LOCAL_EXTENDED_FEATURES_COMMAND_SUPPORTED                      (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_BUFFER_SIZE_COMMAND_SUPPORTED                                  (TRUE  && (BR_EDR_SUPPORTED_CONTROLLER || DUAL_SUPPORTED_CONTROLLER))
// Octet 15
#define HCI_READ_COUNTRY_CODE_COMMAND_SUPPORTED                                 (FALSE && BR_EDR_SUPPORTED_CONTROLLER) /* Deprecated */
#define HCI_READ_BD_ADDR_COMMAND_SUPPORTED                                      (TRUE  && (BR_EDR_SUPPORTED_CONTROLLER || LE_SUPPORTED_CONTROLLER))
#define HCI_READ_FAILED_CONTACT_COUNTER_COMMAND_SUPPORTED                       (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_RESET_FAILED_CONTACT_COUNTER_COMMAND_SUPPORTED                      (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_LINK_QUALITY_COMMAND_SUPPORTED                                 (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_RSSI_COMMAND_SUPPORTED                                         (TRUE  && (BR_EDR_SUPPORTED_CONTROLLER || LE_SUPPORTED_CONTROLLER))
#define HCI_READ_AFH_CHANNEL_MAP_COMMAND_SUPPORTED                              (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_CLOCK_COMMAND_SUPPORTED                                        (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
// Octet 16
#define HCI_READ_LOOPBACK_MODE_COMMAND_SUPPORTED                                (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_WRITE_LOOPBACK_MODE_COMMAND_SUPPORTED                               (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_ENABLE_DEVICE_UNDER_TEST_MODE_COMMAND_SUPPORTED                     (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_SETUP_SYNCHRONOUS_CONNECTION_REQUEST_COMMAND_SUPPORTED              (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_ACCEPT_SYNCHRONOUS_CONNECTION_REQUEST_COMMAND_SUPPORTED             (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_REJECT_SYNCHRONOUS_CONNECTION_REQUEST_COMMAND_SUPPORTED             (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
// Octet 17
#define HCI_READ_EXTENDED_INQUIRY_RESPONSE_COMMAND_SUPPORTED                    (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_WRITE_EXTENDED_INQUIRY_RESPONSE_COMMAND_SUPPORTED                   (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_REFRESH_ENCRYPTION_KEY_COMMAND_SUPPORTED                            (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_SNIFF_SUBRATING_COMMAND_SUPPORTED                                   (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_SIMPLE_PAIRING_MODE_COMMAND_SUPPORTED                          (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_WRITE_SIMPLE_PAIRING_MODE_COMMAND_SUPPORTED                         (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_LOCAL_OOB_DATA_COMMAND_SUPPORTED                               (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
// Octet 18
#define HCI_READ_INQUIRY_RESPONSE_TRANSMIT_POWER_LEVEL_COMMAND_SUPPORTED        (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_WRITE_INQUIRY_TRANSMIT_POWER_LEVEL_COMMAND_SUPPORTED                (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_DEFAULT_ERRONEOUS_DATA_REPORTING_COMMAND_SUPPORTED             (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_WRITE_DEFAULT_ERRONEOUS_DATA_REPORTING_COMMAND_SUPPORTED            (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_IO_CAPABILITY_REQUEST_REPLY_COMMAND_SUPPORTED                       (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
// Octet 19
#define HCI_USER_CONFIRMATION_REQUEST_REPLY_COMMAND_SUPPORTED                   (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_USER_CONFIRMATION_REQUEST_NEGATIVE_REPLY_COMMAND_SUPPORTED          (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_USER_PASSKEY_REQUEST_REPLY_COMMAND_SUPPORTED                        (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_USER_PASSKEY_REQUEST_NEGATIVE_REPLY_COMMAND_SUPPORTED               (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_REMOTE_OOB_DATA_REQUEST_REPLY_COMMAND_SUPPORTED                     (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_WRITE_SIMPLE_PAIRING_DEBUG_MODE_COMMAND_SUPPORTED                   (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_ENHANCED_FLUSH_COMMAND_SUPPORTED                                    (TRUE)
#define HCI_REMOTE_OOB_DATA_REQUEST_NEGATIVE_REPLY_COMMAND_SUPPORTED            (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
// Octet 20
#define HCI_SEND_KEYPRESS_NOTIFICATION_COMMAND_SUPPORTED                        (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_IO_CAPABILITY_REQUEST_NEGATIVE_REPLY_COMMAND_SUPPORTED              (FALSE && BR_EDR_SUPPORTED_CONTROLLER)
#define HCI_READ_ENCRYPTION_KEY_SIZE_COMMAND_SUPPORTED                          (FALSE)
// Octet 21
#define HCI_CREATE_PHYSICAL_LINK_COMMAND_SUPPORTED                              (FALSE)
#define HCI_ACCEPT_PHYSICAL_LINK_COMMAND_SUPPORTED                              (FALSE)
#define HCI_DISCONNECT_PHYSICAL_LINK_COMMAND_SUPPORTED                          (FALSE)
#define HCI_CREATE_LOGICAL_LINK_COMMAND_SUPPORTED                               (FALSE)
#define HCI_ACCEPT_LOGICAL_LINK_COMMAND_SUPPORTED                               (FALSE)
#define HCI_DISCONNECT_LOGICAL_LINK_COMMAND_SUPPORTED                           (FALSE)
#define HCI_LOGICAL_LINK_CANCEL_COMMAND_SUPPORTED                               (FALSE)
#define HCI_FLOW_SPEC_MODIFY_COMMAND_SUPPORTED                                  (FALSE)
// Octet 22
#define HCI_READ_LOGICAL_LINK_ACCEPT_TIMEOUT_COMMAND_SUPPORTED                  (FALSE)
#define HCI_WRITE_LOGICAL_LINK_ACCEPT_TIMEOUT_COMMAND_SUPPORTED                 (FALSE)
#define HCI_SET_EVENT_MASK_PAGE_2_COMMAND_SUPPORTED                             (FALSE)
#define HCI_READ_LOCATION_DATA_COMMAND_SUPPORTED                                (FALSE)
#define HCI_WRITE_LOCATION_DATA_COMMAND_SUPPORTED                               (FALSE)
#define HCI_READ_LOCAL_AMP_INFO_COMMAND_SUPPORTED                               (FALSE)
#define HCI_READ_LOCAL_AMP_ASSOC_COMMAND_SUPPORTED                              (FALSE)
#define HCI_WRITE_REMOTE_AMP_ASSOC_COMMAND_SUPPORTED                            (FALSE)
// Octet 23
#define HCI_READ_FLOW_CONTROL_MODE_COMMAND_SUPPORTED                            (FALSE)
#define HCI_WRITE_FLOW_CONTROL_MODE_COMMAND_SUPPORTED                           (FALSE)
#define HCI_READ_DATA_BLOCK_SIZE_COMMAND_SUPPORTED                              (FALSE)
#define HCI_ENABLE_AMP_RECEIVER_REPORTS_COMMAND_SUPPORTED                       (FALSE)
#define HCI_AMP_TEST_END_COMMAND_SUPPORTED                                      (FALSE)
#define HCI_AMP_TEST_COMMAND_SUPPORTED                                          (FALSE)
// Octet 24
#define HCI_READ_ENHANCED_TRANSMIT_POWER_LEVEL_COMMAND_SUPPORTED                (FALSE)
#define HCI_READ_BEST_EFFORT_FLUSH_TIMEOUT_COMMAND_SUPPORTED                    (FALSE)
#define HCI_WRITE_BEST_EFFORT_FLUSH_TIMEOUT_COMMAND_SUPPORTED                   (FALSE)
#define HCI_SHORT_RANGE_MODE_COMMAND_SUPPORTED                                  (FALSE)
#define HCI_READ_LE_HOST_SUPPORT_COMMAND_SUPPORTED                              (FALSE && DUAL_SUPPORTED_CONTROLLER)
#define HCI_WRITE_LE_HOST_SUPPORT_COMMAND_SUPPORTED                             (FALSE && DUAL_SUPPORTED_CONTROLLER)
// Octet 25
#define HCI_LE_SET_EVENT_MASK_COMMAND_SUPPORTED                                 (TRUE  && LE_SUPPORTED_CONTROLLER)
#define HCI_LE_READ_BUFFER_SIZE_COMMAND_SUPPORTED                               (TRUE  && LE_SUPPORTED_CONTROLLER)
#define HCI_LE_READ_LOCAL_SUPPORTED_FEATURES_COMMAND_SUPPORTED                  (TRUE  && LE_SUPPORTED_CONTROLLER)
#define HCI_LE_SET_RANDOM_ADDRESS_COMMAND_SUPPORTED                             (TRUE  && LE_SUPPORTED_CONTROLLER)
#define HCI_LE_SET_ADVERTISING_PARAMETERS_COMMAND_SUPPORTED                     (TRUE  && LE_SUPPORTED_CONTROLLER)
#define HCI_LE_READ_ADVERTISING_CHANNEL_TX_POWER_COMMAND_SUPPORTED              (TRUE  && LE_SUPPORTED_CONTROLLER)
#define HCI_LE_SET_ADVERTISING_DATA_COMMAND_SUPPORTED                           (TRUE  && LE_SUPPORTED_CONTROLLER)
// Octet 26
#define HCI_LE_SET_SCAN_RESPONSE_DATA_COMMAND_SUPPORTED                         (TRUE  && LE_SUPPORTED_CONTROLLER)
#define HCI_LE_SET_ADVERTISE_ENABLE_COMMAND_SUPPORTED                           (TRUE  && LE_SUPPORTED_CONTROLLER)
#define HCI_LE_SET_SCAN_PARAMETERS_COMMAND_SUPPORTED                            (TRUE  && LE_SUPPORTED_CONTROLLER)
#define HCI_LE_SET_SCAN_ENABLE_COMMAND_SUPPORTED                                (TRUE  && LE_SUPPORTED_CONTROLLER)
#define HCI_LE_CREATE_CONNECTION_COMMAND_SUPPORTED                              (TRUE  && LE_SUPPORTED_CONTROLLER)
#define HCI_LE_CREATE_CONNECTION_CANCEL_COMMAND_SUPPORTED                       (TRUE  && LE_SUPPORTED_CONTROLLER)
#define HCI_LE_READ_WHITE_LIST_SIZE_COMMAND_SUPPORTED                           (TRUE  && LE_SUPPORTED_CONTROLLER)
#define HCI_LE_CLEAR_WHITE_LIST_COMMAND_SUPPORTED                               (TRUE  && LE_SUPPORTED_CONTROLLER)
// Octet 27
#define HCI_LE_ADD_DEVICE_TO_WHITE_LIST_COMMAND_SUPPORTED                       (TRUE  && LE_SUPPORTED_CONTROLLER)
#define HCI_LE_REMOVE_DEVICE_FROM_WHITE_LIST_COMMAND_SUPPORTED                  (TRUE  && LE_SUPPORTED_CONTROLLER)
#define HCI_LE_CONNECTION_UPDATE_COMMAND_SUPPORTED                              (TRUE  && LE_SUPPORTED_CONTROLLER)
#define HCI_LE_SET_HOST_CHANNEL_CLASSIFICATION_COMMAND_SUPPORTED                (TRUE  && LE_SUPPORTED_CONTROLLER)
#define HCI_LE_READ_CHANNEL_MAP_COMMAND_SUPPORTED                               (TRUE  && LE_SUPPORTED_CONTROLLER)
#define HCI_LE_READ_REMOTE_USED_FEATURES_COMMAND_SUPPORTED                      (TRUE  && LE_SUPPORTED_CONTROLLER)
#define HCI_LE_ENCRYPT_COMMAND_SUPPORTED                                        (TRUE  && LE_SUPPORTED_CONTROLLER)
#define HCI_LE_RAND_COMMAND_SUPPORTED                                           (TRUE  && LE_SUPPORTED_CONTROLLER)
// Octet 28
#define HCI_LE_START_ENCRYPTION_COMMAND_SUPPORTED                               (TRUE  && LE_SUPPORTED_CONTROLLER)
#define HCI_LE_LONG_TERM_KEY_REQUEST_REPLY_COMMAND_SUPPORTED                    (TRUE  && LE_SUPPORTED_CONTROLLER)
#define HCI_LE_LONG_TERM_KEY_REQUEST_NEGATIVE_REPLY_COMMAND_SUPPORTED           (TRUE  && LE_SUPPORTED_CONTROLLER)
#define HCI_LE_READ_SUPPORTED_STATES_COMMAND_SUPPORTED                          (TRUE  && LE_SUPPORTED_CONTROLLER)
#define HCI_LE_RECEIVER_TEST_COMMAND_SUPPORTED                                  (TRUE  && LE_SUPPORTED_CONTROLLER)
#define HCI_LE_TRANSMITTER_TEST_COMMAND_SUPPORTED                               (TRUE  && LE_SUPPORTED_CONTROLLER)
#define HCI_LE_TEST_END_COMMAND_SUPPORTED                                       (TRUE  && LE_SUPPORTED_CONTROLLER)
// Octet 29
#define HCI_ENHANCED_SETUP_SYNCHRONOUS_CONNECTION_COMMAND_SUPPORTED             (FALSE)
#define HCI_ENHANCED_ACCEPT_SYNCHRONOUS_CONNECTION_COMMAND_SUPPORTED            (FALSE)
#define HCI_READ_LOCAL_SUPPORTED_CODECS_COMMAND_SUPPORTED                       (FALSE)
#define HCI_SET_MWS_CHANNEL_PARAMETERS_COMMAND_SUPPORTED                        (FALSE)
#define HCI_SET_EXTERNAL_FRAME_CONFIGURATION_COMMAND_SUPPORTED                  (FALSE)
// Octet 30
#define HCI_SET_MWS_SIGNALING_COMMAND_COMMAND_SUPPORTED                         (FALSE)
#define HCI_SET_TRANSPORT_LAYER_COMMAND_COMMAND_SUPPORTED                       (FALSE)
#define HCI_SET_MWS_SCAN_FREQUENCY_TABLE_COMMAND_COMMAND_SUPPORTED              (FALSE)
#define HCI_GET_TRANSPORT_LAYER_CONFIGURATION_COMMAND_COMMAND_SUPPORTED         (FALSE)
#define HCI_SET_MWS_PATTERN_CONFIGURATION_COMMAND_COMMAND_SUPPORTED             (FALSE)
#define HCI_SET_TRIGGERED_CLOCK_CAPTURE_COMMAND_SUPPORTED                       (FALSE)
#define HCI_TRUNCATED_PAGE_COMMAND_SUPPORTED                                    (FALSE)
#define HCI_TRUNCATED_PAGE_CANCEL_COMMAND_SUPPORTED                             (FALSE)
// Octet 31
#define HCI_SET_CONNECTIONLESS_SLAVE_BROADCAST_COMMAND_SUPPORTED                (FALSE)
#define HCI_SET_CONNECTIONLESS_SLAVE_BROADCAST_RECEIVE_COMMAND_SUPPORTED        (FALSE)
#define HCI_START_SYNCHRONIZATION_TRAIN_COMMAND_SUPPORTED                       (FALSE)
#define HCI_RECEIVE_SYNCHRONIZATION_TRAIN_COMMAND_SUPPORTED                     (FALSE)
#define HCI_SET_RESERVED_LT_ADDR_COMMAND_SUPPORTED                              (FALSE)
#define HCI_DELETE_RESERVED_LT_ADDR_COMMAND_SUPPORTED                           (FALSE)
#define HCI_SET_CONNECTIONLESS_SLAVE_BROADCAST_DATA_COMMAND_SUPPORTED           (FALSE)
#define HCI_READ_SYNCHRONIZATION_TRAIN_PARAMETERS_COMMAND_SUPPORTED             (FALSE)
// Octet 32
#define HCI_WRITE_SYNCHRONIZATION_TRAIN_PARAMETERS_COMMAND_SUPPORTED            (FALSE)
#define HCI_REMOTE_OOB_EXTENDED_DATA_REQUEST_REPLY_COMMAND_SUPPORTED            (FALSE)
#define HCI_READ_SECURE_CONNECTIONS_HOST_SUPPORT_COMMAND_SUPPORTED              (FALSE)
#define HCI_WRITE_SECURE_CONNECTIONS_HOST_SUPPORT_COMMAND_SUPPORTED             (FALSE)
#define HCI_READ_AUTHENTICATED_PAYLOAD_TIMEOUT_COMMAND_SUPPORTED                (FALSE)
#define HCI_WRITE_AUTHENTICATED_PAYLOAD_TIMEOUT_COMMAND_SUPPORTED               (FALSE)
#define HCI_READ_LOCAL_OOB_EXTENDED_DATA_COMMAND_SUPPORTED                      (FALSE)
#define HCI_WRITE_SECURE_CONNECTIONS_TEST_MODE_COMMAND_SUPPORTED                (FALSE)
// Octet 33
#define HCI_READ_EXTENDED_PAGE_TIMEOUT_COMMAND_SUPPORTED                        (FALSE)
#define HCI_WRITE_EXTENDED_PAGE_TIMEOUT_COMMAND_SUPPORTED                       (FALSE)
#define HCI_READ_EXTENDED_INQUIRY_LENGTH_COMMAND_SUPPORTED                      (FALSE)
#define HCI_WRITE_EXTENDED_INQUIRY_LENGTH_COMMAND_SUPPORTED                     (FALSE)
#define HCI_LE_REMOTE_CONNECTION_PARAMETER_REQUEST_REPLY_COMMAND_SUPPORTED      (FALSE)
#define HCI_LE_REMOTE_CONNECTION_PARAMETER_REQUEST_NEGATIVE_REPLY_COMMAND_SUPPORTED (FALSE)

#define HCI_LE_SET_DATA_LENGTH_COMMAND_SUPPORTED                                TRUE  && (LE_SUPPORTED_CONTROLLER)
#define HCI_LE_READ_SUGGESTED_DEFAULT_DATA_LENGTH_COMMAND_SUPPORTED             TRUE  && (LE_SUPPORTED_CONTROLLER)
#define HCI_LE_WRITE_SUGGESTED_DEFAULT_DATA_LENGTH_COMMAND_SUPPORTED            TRUE  && (LE_SUPPORTED_CONTROLLER)

#endif /* _BT_CONFIG_H_ */
