#if defined(SUPPORT_VOICE_PROMPT) || defined(SUPPORT_VOICE_COMMAND)
SECTORS_ENUM_MACRO(SECTOR_VOICE_LANG_CTL, &gVoiceLangCtl, (sizeof(VoiceLangCtl) * LANG_COUNT), CRC_NOT_CHK)
#else
SECTORS_ENUM_MACRO(SECTOR_VOICE_LANG_CTL, NULL, 0, CRC_NOT_CHK)
#endif

#ifdef SUPPORT_VOICE_COMMAND
SECTORS_ENUM_MACRO(SECTOR_VOICE_COMMAND_DATA, &gDriverVoiceCommandData, sizeof(SECTOR_DRIVER_VOICE_COMMAND_STRU), CRC_NOT_CHK)
#else
SECTORS_ENUM_MACRO(SECTOR_VOICE_COMMAND_DATA, NULL, 0, CRC_NOT_CHK)
#endif	
