#if defined(SELFIE_App)
    #if defined(BLUETOOTH_SPEAKER)
        #define KEY_TAP_ACTION	\
            {KEY1, KEY_ACPCALL,(KEY_MAP_MMI_HFP_INCOMMING|KEY_MAP_MMI_TWS_PAIRING)},														\
            {KEY1, KEY_ENDCALL, (KEY_MAP_MMI_HFP_CALLACTIVE|KEY_MAP_MMI_TWS_PAIRING|								\
															KEY_MAP_MMI_HFP_CALLACTIVE_WITHOUT_SCO	)},				\
            {KEY1, KEY_RECONNECT_USER_INIT, (KEY_MAP_MMI_CONDISCABLE|KEY_MAP_MMI_CONNECTABLE|						\
												KEY_MAP_MMI_CONNECTED|KEY_MAP_MMI_LINE_IN)},						\
            {KEY1, KEY_CNLOUTGOING, (KEY_MAP_MMI_HFP_OUTGOING|KEY_MAP_MMI_HFP_CAOGG|KEY_MAP_MMI_TWS_PAIRING)},		\
            /* A2DP */																								\
            {KEY5, KEY_AVRCP_PLAY, KEY_MAP_MMI_CONNECTED|KEY_MAP_MMI_TWS_PAIRING},									\
            /*{KEY5, KEY_AVRCP_STOP,KEY_MAP_MMI_CONNECTED},*/														\
            {KEY3, KEY_AVRCP_FORWARD,KEY_MAP_MMI_CONNECTED|KEY_MAP_MMI_TWS_PAIRING},								\
            {KEY4, KEY_AVRCP_BACKWARD,KEY_MAP_MMI_CONNECTED|KEY_MAP_MMI_TWS_PAIRING},								\
            /* 3 way calling */																						\
            {KEY3, KEY_3WAYRELNACP,(KEY_MAP_MMI_HFP_CAIMG|KEY_MAP_MMI_HFP_CAMULTY|KEY_MAP_MMI_TWS_PAIRING)},		\
            {KEY4, KEY_3WAYHOLDNACP, (KEY_MAP_MMI_HFP_CAIMG|KEY_MAP_MMI_HFP_CAMULTY|KEY_MAP_MMI_TWS_PAIRING)},		\
            {KEY6, KEY_3WAYRELNUDUB, (KEY_MAP_MMI_HFP_CAIMG|KEY_MAP_MMI_HFP_CAMULTY|KEY_MAP_MMI_TWS_PAIRING)},		\
            /* Test mode */																							\
            {KEY1, KEY_SWITCH_TEST_MODE_STATE, KEY_MAP_MMI_TEST_MODE},												\
            {KEY3, KEY_SWITCH_TEST_MODE_CHANNEL, KEY_MAP_MMI_TEST_MODE},											\
            {KEY4, KEY_SWITCH_TEST_MODE_POWER, KEY_MAP_MMI_TEST_MODE},												\
            {KEY5, KEY_SWITCH_TEST_MODE_TX_PACKET_TYPE, KEY_MAP_MMI_TEST_MODE},		                                \
            /* HID */                                                                                               \
            {KEY8, KEY_SELFIE, (KEY_MAP_MMI_CONNECTED|KEY_MAP_MMI_TWS_PAIRING},                                                
    #else
        #define KEY_TAP_ACTION	\
            {KEY1, KEY_ACPCALL,(KEY_MAP_MMI_HFP_INCOMMING|KEY_MAP_MMI_TWS_PAIRING)},								\
            {KEY1, KEY_ENDCALL, (KEY_MAP_MMI_HFP_CALLACTIVE|KEY_MAP_MMI_TWS_PAIRING|								\
															KEY_MAP_MMI_HFP_CALLACTIVE_WITHOUT_SCO)},				\
            {KEY1, KEY_RECONNECT_USER_INIT, (KEY_MAP_MMI_CONDISCABLE|KEY_MAP_MMI_CONNECTABLE|						\
												KEY_MAP_MMI_CONNECTED|KEY_MAP_MMI_LINE_IN)},						\
            {KEY1, KEY_CNLOUTGOING, (KEY_MAP_MMI_HFP_OUTGOING|KEY_MAP_MMI_HFP_CAOGG|KEY_MAP_MMI_TWS_PAIRING)},		\
            /* A2DP */																								\
            {KEY5, KEY_AVRCP_PLAY, KEY_MAP_MMI_CONNECTED|KEY_MAP_MMI_TWS_PAIRING},									\
            /*{KEY5, KEY_AVRCP_STOP,KEY_MAP_MMI_CONNECTED},*/														\
            {KEY3, KEY_AVRCP_FORWARD,KEY_MAP_MMI_CONNECTED|KEY_MAP_MMI_TWS_PAIRING},								\
            {KEY4, KEY_AVRCP_BACKWARD,KEY_MAP_MMI_CONNECTED|KEY_MAP_MMI_TWS_PAIRING},								\
            /* 3 way calling */																						\
            {KEY3, KEY_3WAYRELNACP,(KEY_MAP_MMI_HFP_CAIMG|KEY_MAP_MMI_TWS_PAIRING|KEY_MAP_MMI_HFP_CAMULTY)},		\
            {KEY4, KEY_3WAYHOLDNACP, (KEY_MAP_MMI_HFP_CAIMG|KEY_MAP_MMI_TWS_PAIRING|KEY_MAP_MMI_HFP_CAMULTY)},		\
            {KEY6, KEY_3WAYRELNUDUB, (KEY_MAP_MMI_HFP_CAIMG|KEY_MAP_MMI_TWS_PAIRING|KEY_MAP_MMI_HFP_CAMULTY)},		\
            /* Test mode */																							\
            {KEY1, KEY_SWITCH_TEST_MODE_STATE, KEY_MAP_MMI_TEST_MODE},												\
            {KEY3, KEY_SWITCH_TEST_MODE_CHANNEL, KEY_MAP_MMI_TEST_MODE},											\
            {KEY4, KEY_SWITCH_TEST_MODE_POWER, KEY_MAP_MMI_TEST_MODE},												\
            {KEY5, KEY_SWITCH_TEST_MODE_TX_PACKET_TYPE, KEY_MAP_MMI_TEST_MODE},		                                \
            /* HID */                                                                                               \
           {KEY6, KEY_SELFIE, (KEY_MAP_MMI_CONNECTED|KEY_MAP_MMI_TWS_PAIRING)},
    #endif

#else
#define KEY_TAP_ACTION	\
		{KEY1, KEY_ACPCALL,(KEY_MAP_MMI_HFP_INCOMMING|KEY_MAP_MMI_TWS_PAIRING)},									\
		{KEY1, KEY_ENDCALL, (KEY_MAP_MMI_HFP_CALLACTIVE|KEY_MAP_MMI_TWS_PAIRING|									\
															KEY_MAP_MMI_HFP_CALLACTIVE_WITHOUT_SCO)},				\
		{KEY1, KEY_RECONNECT_USER_INIT, (KEY_MAP_MMI_CONDISCABLE|KEY_MAP_MMI_CONNECTABLE|							\
											KEY_MAP_MMI_CONNECTED|KEY_MAP_MMI_LINE_IN)},							\
		{KEY1, KEY_CNLOUTGOING, (KEY_MAP_MMI_HFP_OUTGOING|KEY_MAP_MMI_HFP_CAOGG|KEY_MAP_MMI_TWS_PAIRING)},			\
		/* A2DP */																									\
		{KEY5, KEY_AVRCP_PLAY, KEY_MAP_MMI_CONNECTED|KEY_MAP_MMI_TWS_PAIRING},										\
		/*{KEY5, KEY_AVRCP_STOP,KEY_MAP_MMI_CONNECTED},*/															\
		{KEY3, KEY_AVRCP_FORWARD,KEY_MAP_MMI_CONNECTED|KEY_MAP_MMI_TWS_PAIRING},									\
		{KEY4, KEY_AVRCP_BACKWARD,KEY_MAP_MMI_CONNECTED|KEY_MAP_MMI_TWS_PAIRING},									\
		/* 3 way calling */																							\
		{KEY3, KEY_3WAYRELNACP,(KEY_MAP_MMI_HFP_CAIMG|KEY_MAP_MMI_HFP_CAMULTY|KEY_MAP_MMI_TWS_PAIRING)},			\
		{KEY4, KEY_3WAYHOLDNACP, (KEY_MAP_MMI_HFP_CAIMG|KEY_MAP_MMI_HFP_CAMULTY|KEY_MAP_MMI_TWS_PAIRING)},			\
		{KEY6, KEY_3WAYRELNUDUB, (KEY_MAP_MMI_HFP_CAIMG|KEY_MAP_MMI_HFP_CAMULTY|KEY_MAP_MMI_TWS_PAIRING)},			\
		/* Test mode */																								\
		{KEY1, KEY_SWITCH_TEST_MODE_STATE, KEY_MAP_MMI_TEST_MODE},													\
		{KEY3, KEY_SWITCH_TEST_MODE_CHANNEL, KEY_MAP_MMI_TEST_MODE},												\
		{KEY4, KEY_SWITCH_TEST_MODE_POWER, KEY_MAP_MMI_TEST_MODE},													\
		{KEY5, KEY_SWITCH_TEST_MODE_TX_PACKET_TYPE, KEY_MAP_MMI_TEST_MODE},											\
		
#endif		
								 
#define KEY_PRESS_ACTION	\
		{KEY1, KEY_MEDIA_TRIGGER_1, (KEY_MAP_MMI_CONNECTABLE|KEY_MAP_MMI_CONNECTED|									\
									KEY_MAP_MMI_HFP_INCOMMING|KEY_MAP_MMI_HFP_CALLACTIVE|							\
									KEY_MAP_MMI_HFP_CALLACTIVE_WITHOUT_SCO|KEY_MAP_MMI_HFP_CAIMG|					\
									KEY_MAP_MMI_HFP_CAOGG|KEY_MAP_MMI_HFP_CAMULTY|KEY_MAP_MMI_LINE_IN)},			\
		{KEY5, KEY_DISCOVERABLE,	KEY_MAP_MMI_CONNECTABLE|KEY_MAP_MMI_CONDISCABLE|								\
									KEY_MAP_MMI_CONNECTED|KEY_MAP_MMI_LINE_IN},										\
		{KEY_COMB_34, KEY_VOICE_PROMPT_LANG_CHANGE, KEY_MAP_MMI_CONDISCABLE|KEY_MAP_MMI_CONNECTABLE|				\
														KEY_MAP_MMI_CONNECTED | KEY_MAP_MMI_TWS_PAIRING},			\
		

#define KEY_PRESS_RELEASE_ACTION	\
		{KEY1, KEY_RESET,(KEY_MAP_MMI_EEPROM_UPDATING)},															\
		{KEY1, KEY_REJCALL, 		KEY_MAP_MMI_HFP_INCOMMING|KEY_MAP_MMI_TWS_PAIRING},								\
		{KEY1, KEY_RDIAL, (KEY_MAP_MMI_CONNECTED|KEY_MAP_MMI_LINE_IN|KEY_MAP_MMI_FM|KEY_MAP_MMI_TWS_PAIRING)},		\
		{KEY1, KEY_ONHOLD_CALL, KEY_MAP_MMI_HFP_CALLACTIVE|KEY_MAP_MMI_TWS_PAIRING|									\
														KEY_MAP_MMI_HFP_CALLACTIVE_WITHOUT_SCO},					\

#if defined(BLUETOOTH_SPEAKER)
	#define KEY_LONG_PRESS_ACTION	\
			{KEY1, KEY_POWER_OFF, KEY_MAP_MMI_ALL_STATES & ~(KEY_MAP_MMI_OFF|KEY_MAP_MMI_FAKEOFF|KEY_MAP_MMI_FAKEON|\
									KEY_MAP_MMI_EEPROM_UPDATED_OK|KEY_MAP_MMI_EEPROM_UPDATED_FAIL|					\
									KEY_MAP_MMI_EEPROM_UPDATING|KEY_MAP_MMI_DETACHING_LINK)},						\
			{KEY1, KEY_POWER_ON, (KEY_MAP_MMI_FAKEOFF|KEY_MAP_MMI_FAKEON)},											\
			{KEY10, KEY_ENTER_LINEIN_MODE,( KEY_MAP_MMI_CONDISCABLE|KEY_MAP_MMI_TWS_PAIRING|						\
											KEY_MAP_MMI_CONNECTABLE|KEY_MAP_MMI_CONNECTED|							\
											KEY_MAP_MMI_HFP_INCOMMING|KEY_MAP_MMI_HFP_OUTGOING|						\
											KEY_MAP_MMI_HFP_CAOGG|KEY_MAP_MMI_HFP_CALLACTIVE|						\
											KEY_MAP_MMI_HFP_CALLACTIVE_WITHOUT_SCO|									\
											KEY_MAP_MMI_HFP_CAIMG|KEY_MAP_MMI_HFP_CAMULTY)},						\
			{KEY_COMB_14, KEY_RESET_PAIRED_DEVICES, KEY_MAP_MMI_FAKEOFF|KEY_MAP_MMI_FAKEON},
#else
	#define KEY_LONG_PRESS_ACTION	\
			{KEY1, KEY_POWER_OFF, KEY_MAP_MMI_ALL_STATES & ~(KEY_MAP_MMI_OFF|KEY_MAP_MMI_FAKEOFF|KEY_MAP_MMI_FAKEON|\
									KEY_MAP_MMI_EEPROM_UPDATED_OK|KEY_MAP_MMI_EEPROM_UPDATED_FAIL|					\
									KEY_MAP_MMI_EEPROM_UPDATING|KEY_MAP_MMI_DETACHING_LINK)},						\
			{KEY1, KEY_POWER_ON, (KEY_MAP_MMI_FAKEOFF|KEY_MAP_MMI_FAKEON)},											\
			{KEY10, KEY_ENTER_LINEIN_MODE,( KEY_MAP_MMI_CONDISCABLE|KEY_MAP_MMI_TWS_PAIRING|						\
											KEY_MAP_MMI_CONNECTABLE|KEY_MAP_MMI_CONNECTED|							\
											KEY_MAP_MMI_HFP_INCOMMING|KEY_MAP_MMI_HFP_OUTGOING|						\
											KEY_MAP_MMI_HFP_CAOGG|KEY_MAP_MMI_HFP_CALLACTIVE|						\
											KEY_MAP_MMI_HFP_CALLACTIVE_WITHOUT_SCO|									\
											KEY_MAP_MMI_HFP_CAIMG|KEY_MAP_MMI_HFP_CAMULTY)},						\
			{KEY6, KEY_VOICE_COMMAND_ENABLE, (KEY_MAP_MMI_CONDISCABLE|KEY_MAP_MMI_CONNECTABLE|						\
												KEY_MAP_MMI_CONNECTED |KEY_MAP_MMI_TWS_PAIRING )},					\
			{KEY_COMB_14, KEY_RESET_PAIRED_DEVICES, KEY_MAP_MMI_FAKEOFF|KEY_MAP_MMI_FAKEON},
#endif

#define KEY_LONG_PRESS_RELEASE_ACTION	\
		{KEY1, KEY_RECONNECT_AFTER_POWER_ON, KEY_MAP_MMI_CONNECTABLE|KEY_MAP_MMI_FAKEON},							\
		{KEY10, KEY_EXIT_LINEIN_MODE,(  KEY_MAP_MMI_LINE_IN|KEY_MAP_MMI_TWS_PAIRING|								\
										KEY_MAP_MMI_CONDISCABLE|KEY_MAP_MMI_CONNECTABLE|							\
											KEY_MAP_MMI_CONNECTED|KEY_MAP_MMI_HFP_INCOMMING|						\
											KEY_MAP_MMI_HFP_OUTGOING|KEY_MAP_MMI_HFP_CAOGG|							\
											KEY_MAP_MMI_HFP_CALLACTIVE|												\
										KEY_MAP_MMI_HFP_CALLACTIVE_WITHOUT_SCO|										\
										KEY_MAP_MMI_HFP_CAIMG|KEY_MAP_MMI_HFP_CAMULTY)},							\

#define KEY_DOUBLE_ACTION	\
		{KEY5, KEY_MIC_MUTE_TOGGLE, (KEY_MAP_MMI_HFP_CALLACTIVE|KEY_MAP_MMI_HFP_CAMULTY|KEY_MAP_MMI_TWS_PAIRING)},	\
		{KEY6, KEY_3WAYADD, (KEY_MAP_MMI_HFP_CAIMG|KEY_MAP_MMI_HFP_CAMULTY|KEY_MAP_MMI_TWS_PAIRING)},				\
		{KEY1, KEY_SET_VOICE_RECOGNITION,KEY_MAP_MMI_CONNECTED},													\

#define KEY_TRIPLE_ACTION	\
		{KEY1, KEY_ENTER_TESTMODE,KEY_MAP_MMI_CONDISCABLE},															\
		{KEY6, KEY_CONNECTED_TO_CONNECTABLE, KEY_MAP_MMI_CONNECTED|KEY_MAP_MMI_HFP_INCOMMING|KEY_MAP_MMI_HFP_CALLACTIVE|	\
									KEY_MAP_MMI_HFP_CALLACTIVE_WITHOUT_SCO|KEY_MAP_MMI_HFP_CAIMG|					\
									KEY_MAP_MMI_HFP_CAOGG|KEY_MAP_MMI_HFP_CAMULTY|KEY_MAP_MMI_LINE_IN},				\

#define KEY_LONG_LONG_PRESS_ACTION																				\
		{KEY1, KEY_AIR_ENTER_AIR_PAIRING, KEY_MAP_MMI_CONNECTABLE|KEY_MAP_MMI_LINE_IN},							\
		
/*#define KEY_LONG_LONG_PRESS_RELEASE_ACTION											\	*/
		
/*#define KEY_EXTREMELY_LONG_PRESS_ACTION												\	*/

/* #define KEY_EXTREMELY_LONG_PRESS_RELEASE_ACTION										\	*/

#define KEY_REPEAT_ACTION	\
		{KEY3, KEY_VOICEUP,(KEY_MAP_MMI_LINE_IN|KEY_MAP_MMI_FM|KEY_MAP_MMI_CONNECTED|							\
							KEY_MAP_MMI_HFP_INCOMMING|KEY_MAP_MMI_HFP_OUTGOING|									\
							KEY_MAP_MMI_HFP_CALLACTIVE|KEY_MAP_MMI_HFP_CAIMG|KEY_MAP_MMI_TWS_PAIRING|			\
							KEY_MAP_MMI_HFP_CAOGG|KEY_MAP_MMI_HFP_CAMULTY|KEY_MAP_MMI_LINE_IN)},				\
		{KEY4, KEY_VOICEDN,(KEY_MAP_MMI_LINE_IN|KEY_MAP_MMI_FM|KEY_MAP_MMI_CONNECTED|							\
							KEY_MAP_MMI_HFP_INCOMMING|KEY_MAP_MMI_HFP_OUTGOING|									\
							KEY_MAP_MMI_HFP_CALLACTIVE|KEY_MAP_MMI_HFP_CAIMG|KEY_MAP_MMI_TWS_PAIRING|			\
							KEY_MAP_MMI_HFP_CAOGG|KEY_MAP_MMI_HFP_CAMULTY|KEY_MAP_MMI_LINE_IN)},				\

//#define KEY_DOWN_ACTION

//#define KEY_UP_ACTION

//#define KEY_NOACT_ACTION
