SECTORS_ENUM_MACRO(SECTOR_SYS_LOCAL_DEVICE_INFO, &gSector_SysLocalDeviceInfo, sizeof(SYS_LOCAL_DEVICE_INFO_STRU), CRC_CHK)

SECTORS_ENUM_MACRO(SECTOR_SYS_LOCAL_DEVICE_EIR, &gSector_SysLocalDeviceEIR, sizeof(SYS_LOCAL_DEVICE_EIR_STRU), CRC_CHK)

SECTORS_ENUM_MACRO(SECTOR_SYS_LOCAL_DEVICE_CONTROL, &gSector_SysLocalDeviceControl, sizeof(SYS_LOCAL_DEVICE_CONTROL_STRU), CRC_CHK)

SECTORS_ENUM_MACRO(SECTOR_MISC_CTL_INIT, &gMISC_ctl_init, sizeof(LC_MISC_CONTROL), CRC_CHK)

SECTORS_ENUM_MACRO(SECTOR_LM_PARAMETER, &gSector_LmParameter, sizeof(LM_PARAMETER_STRU), CRC_CHK)

SECTORS_ENUM_MACRO(SECTOR_HC_PARAMETER_INIT, &gHC_parameter_init, sizeof(HC_PARAMETER_TYPE), CRC_CHK)

SECTORS_ENUM_MACRO(SECTOR_UART_PARAMETER, &gSector_UartParameter, sizeof(UART_PARAMETER_STRU), CRC_CHK)

SECTORS_ENUM_MACRO(SECTOR_MCU_DSP_PARAMETER_INIT, &gMcu_dsp_parameter_init, sizeof(DSP_NVRAM_CTL_TYPE), CRC_CHK)

#ifdef A2DP_Profile
SECTORS_ENUM_MACRO(SECTOR_A2DP_NVRAM_CTL_INIT, &gA2DP_nvram_ctl_init, sizeof(A2DP_NVRAM_CTL_TYPE), CRC_CHK)
#else
SECTORS_ENUM_MACRO(SECTOR_A2DP_NVRAM_CTL_INIT, NULL, 0, CRC_NOT_CHK)
#endif

SECTORS_ENUM_MACRO(SECTOR_DRIVER_LED_DATA_INIT, &gDriver_led_data_init, sizeof(DRIVER_LED_DATA_TYPE), CRC_CHK)

SECTORS_ENUM_MACRO(SECTOR_DRIVER_RESERVED_DATA_INIT, &gDriver_reserved_data_init, sizeof(DRIVER_RESERVED_DATA_TYPE), CRC_CHK)

SECTORS_ENUM_MACRO(SECTOR_DRIVER_RINGTONE_DATA_INIT, &gDriver_ringtone_data_init, sizeof(DRIVER_RINGTONE_DATA_TYPE), CRC_CHK)

SECTORS_ENUM_MACRO(SECTOR_MMI_DRIVER_V_NVRAM_BACKUP, &gMMI_Driver_v_nvram_backup, sizeof(MMI_DRIVER_NVRAM_BACKUP_TYPE), CRC_CHK)

SECTORS_ENUM_MACRO(SECTOR_MMI_NVRAM_INIT, &gMMI_nvram_init, sizeof(MMI_NVRAM_TYPE), CRC_CHK)

SECTORS_ENUM_MACRO(SECTOR_MMI_NVRAM_KEYMAP_INIT, &gMMI_nvram_keymap_init, sizeof(MMI_NVRAM_KEYMAP), CRC_CHK)

SECTORS_ENUM_MACRO(SECTOR_SYS_MEMORY_CONFIG, &gSector_SysMemoryConfig, sizeof(SYS_MEMORY_CONFIG_STRU), CRC_CHK)

SECTORS_ENUM_MACRO(SECTOR_SM_NVRAM_INIT, &gSM_nvram_init, sizeof(SM_NVRAM_TYPE), CRC_CHK)

SECTORS_ENUM_MACRO(SECTOR_GAP_NVRAM_INIT, &gGAP_nvram_init, sizeof(GAP_NVRAM_TYPE), CRC_CHK)

SECTORS_ENUM_MACRO(SECTOR_DRIVER_CTL_INIT, &gDriver_ctl_init, sizeof(DRIVER_CTL_TYPE), CRC_CHK)

#ifdef AB1520B
SECTORS_ENUM_MACRO(SECTOR_MMI_LE_NVRAM_INIT, &gMMI_le_nvram_init, sizeof(MMI_LE_NVRAM_TYPE), CRC_CHK)
#endif

SECTORS_ENUM_MACRO(SECTOR_APPLICATION_INIT, &gApplication_init, sizeof(APPLICATION_STRU), CRC_CHK)

#ifdef IAP2_Profile
SECTORS_ENUM_MACRO(SECTOR_IAP2_SYNC_PAYLOAD, &gIAP2_Sync_Payload, sizeof(IAP2SyncPayload), CRC_CHK)
SECTORS_ENUM_MACRO(SECTOR_IAP2_IDEN_PARAM, &gIAP2_Iden_Param, sizeof(IAP2IdenParam), CRC_CHK)
#else
SECTORS_ENUM_MACRO(SECTOR_IAP2_SYNC_PAYLOAD, NULL, 0, CRC_NOT_CHK)
SECTORS_ENUM_MACRO(SECTOR_IAP2_IDEN_PARAM, NULL, 0, CRC_NOT_CHK)
#endif

#if LE_SUPPORTED_CONTROLLER
SECTORS_ENUM_MACRO(SECTOR_LE_MISC_CTL_INIT, &gLE_MISC_Ctl_Init, sizeof(LE_MISC_CONTROL_STRU), CRC_CHK)
#else
SECTORS_ENUM_MACRO(SECTOR_LE_MISC_CTL_INIT, NULL, 0, CRC_NOT_CHK)
#endif

#ifndef AB1520B
SECTORS_ENUM_MACRO(SECTOR_SYS_PATCH_CODE_INIT, &gSector_SysPatchCodeInit, sizeof(PATCH_CODE_INIT_STRU), CRC_CHK)
#endif

#if (HW_SPI_SUPPORTED)
SECTORS_ENUM_MACRO(SECTOR_SPI_CONFIG, &gSectorSpiConfig, sizeof(SPI_CONFIG_STRU), CRC_CHK)
#else
SECTORS_ENUM_MACRO(SECTOR_SPI_CONFIG, NULL, 0, CRC_NOT_CHK)
#endif

#ifdef DSP_ENABLE
SECTORS_ENUM_MACRO(SECTOR_DSP_PEQ_PARAMETER, &gSector_DspPeqParameter, sizeof(DSP_PEQ_PARAMETER_STRU), CRC_CHK)
#else
SECTORS_ENUM_MACRO(SECTOR_DSP_PEQ_PARAMETER, NULL, 0, CRC_NOT_CHK)
#endif

#ifdef DSP_ENABLE
SECTORS_ENUM_MACRO(SECTOR_DSP_HPF_PARAMETER, &gSector_DspHpfParameter, sizeof(DSP_HPF_PARAMETER_STRU), CRC_CHK)
#else
SECTORS_ENUM_MACRO(SECTOR_DSP_HPF_PARAMETER, NULL, 0, CRC_NOT_CHK)
#endif